// Single-file project generation utilities

export interface ProjectTemplate {
  name: string
  description: string
  generateContent: (customContent?: string) => string
}

/**
 * Generate a complete HTML document with all dependencies inline
 */
export function generateSingleFileProject(
  html: string = '',
  css: string = '',
  js: string = '',
  options: {
    title?: string
    description?: string
    author?: string
    viewport?: string
    includeModernReset?: boolean
    includeUtilities?: boolean
  } = {}
): string {
  const {
    title = 'Generated Website',
    description = 'A website generated by AI',
    author = 'AI Assistant',
    viewport = 'width=device-width, initial-scale=1.0',
    includeModernReset = true,
    includeUtilities = true
  } = options

  const modernReset = includeModernReset ? `
    /* Modern CSS Reset */
    *, *::before, *::after {
      box-sizing: border-box;
    }
    
    * {
      margin: 0;
      padding: 0;
    }
    
    html, body {
      height: 100%;
    }
    
    body {
      line-height: 1.6;
      -webkit-font-smoothing: antialiased;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
    }
    
    img, picture, video, canvas, svg {
      display: block;
      max-width: 100%;
    }
    
    input, button, textarea, select {
      font: inherit;
    }
    
    p, h1, h2, h3, h4, h5, h6 {
      overflow-wrap: break-word;
    }
    
    #root, #__next {
      isolation: isolate;
    }
  ` : ''

  const utilities = includeUtilities ? `
    /* Utility Classes */
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 0 1rem;
    }
    
    .text-center { text-align: center; }
    .text-left { text-align: left; }
    .text-right { text-align: right; }
    
    .flex { display: flex; }
    .flex-col { flex-direction: column; }
    .items-center { align-items: center; }
    .justify-center { justify-content: center; }
    .justify-between { justify-content: space-between; }
    
    .grid { display: grid; }
    .grid-2 { grid-template-columns: repeat(2, 1fr); }
    .grid-3 { grid-template-columns: repeat(3, 1fr); }
    .grid-4 { grid-template-columns: repeat(4, 1fr); }
    
    .gap-1 { gap: 0.25rem; }
    .gap-2 { gap: 0.5rem; }
    .gap-4 { gap: 1rem; }
    .gap-8 { gap: 2rem; }
    
    .p-4 { padding: 1rem; }
    .p-8 { padding: 2rem; }
    .py-4 { padding-top: 1rem; padding-bottom: 1rem; }
    .px-4 { padding-left: 1rem; padding-right: 1rem; }
    
    .m-4 { margin: 1rem; }
    .my-4 { margin-top: 1rem; margin-bottom: 1rem; }
    .mx-auto { margin-left: auto; margin-right: auto; }
    
    .w-full { width: 100%; }
    .h-full { height: 100%; }
    .min-h-screen { min-height: 100vh; }
    
    .rounded { border-radius: 0.375rem; }
    .rounded-lg { border-radius: 0.5rem; }
    .shadow { box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); }
    .shadow-lg { box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1); }
    
    @media (max-width: 768px) {
      .grid-2, .grid-3, .grid-4 {
        grid-template-columns: 1fr;
      }
      
      .container {
        padding: 0 0.5rem;
      }
    }
  ` : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="${viewport}">
    <meta name="description" content="${description}">
    <meta name="author" content="${author}">
    <title>${title}</title>
    
    <!-- Favicon -->
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🌐</text></svg>">
    
    <style>
        ${modernReset}
        ${utilities}
        
        /* Custom Styles */
        ${css}
        
        /* Loading Animation */
        .loading {
            opacity: 0;
            animation: fadeIn 0.5s ease-in-out forwards;
        }
        
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }
        
        /* Smooth Scrolling */
        html {
            scroll-behavior: smooth;
        }
        
        /* Print Styles */
        @media print {
            * {
                background: transparent !important;
                color: black !important;
                box-shadow: none !important;
                text-shadow: none !important;
            }
        }
    </style>
</head>
<body>
    <div id="app" class="loading">
        ${html}
    </div>
    
    <script>
        // Error Handling
        window.onerror = function(msg, url, line, col, error) {
            console.error('Error:', msg, 'at line', line);
            return false;
        };
        
        // Modern Promise-based error handling
        window.addEventListener('unhandledrejection', function(event) {
            console.error('Unhandled promise rejection:', event.reason);
        });
        
        // DOM Ready
        document.addEventListener('DOMContentLoaded', function() {
            console.log('Page loaded successfully!');
            
            // Add loading animation
            const app = document.getElementById('app');
            if (app) {
                app.classList.add('loading');
            }
            
            // Custom JavaScript
            ${js}
        });
        
        // Utility Functions
        function $(selector) {
            return document.querySelector(selector);
        }
        
        function $$(selector) {
            return document.querySelectorAll(selector);
        }
        
        // Simple event delegation
        function on(event, selector, handler) {
            document.addEventListener(event, function(e) {
                if (e.target.matches(selector)) {
                    handler.call(e.target, e);
                }
            });
        }
        
        // Smooth scroll to element
        function scrollTo(selector) {
            const element = $(selector);
            if (element) {
                element.scrollIntoView({ behavior: 'smooth' });
            }
        }
    </script>
</body>
</html>`
}

/**
 * Project templates for common website types
 */
export const projectTemplates: ProjectTemplate[] = [
  {
    name: 'Portfolio Website',
    description: 'A professional portfolio website with hero, about, skills, projects, and contact sections',
    generateContent: (customContent = '') => {
      const html = `
        <!-- Navigation -->
        <nav class="navbar">
            <div class="container">
                <div class="nav-brand">
                    <h2>Your Name</h2>
                </div>
                <ul class="nav-menu">
                    <li><a href="#home" class="nav-link">Home</a></li>
                    <li><a href="#about" class="nav-link">About</a></li>
                    <li><a href="#skills" class="nav-link">Skills</a></li>
                    <li><a href="#projects" class="nav-link">Projects</a></li>
                    <li><a href="#contact" class="nav-link">Contact</a></li>
                </ul>
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
        </nav>

        <!-- Hero Section -->
        <section id="home" class="hero">
            <div class="container">
                <div class="hero-content">
                    <h1 class="hero-title">Hello, I'm a <span class="highlight">Web Developer</span></h1>
                    <p class="hero-description">I create beautiful and functional web experiences</p>
                    <div class="hero-buttons">
                        <a href="#projects" class="btn btn-primary">View Projects</a>
                        <a href="#contact" class="btn btn-secondary">Contact Me</a>
                    </div>
                </div>
            </div>
        </section>

        <!-- About Section -->
        <section id="about" class="about">
            <div class="container">
                <h2 class="section-title">About Me</h2>
                <div class="about-content">
                    <div class="about-text">
                        <p>I'm a passionate web developer with experience in creating modern, responsive websites. I love turning ideas into reality through clean, efficient code.</p>
                        <p>With expertise in HTML, CSS, JavaScript, and modern frameworks, I build websites that not only look great but also provide excellent user experiences.</p>
                    </div>
                </div>
            </div>
        </section>

        <!-- Skills Section -->
        <section id="skills" class="skills">
            <div class="container">
                <h2 class="section-title">Skills</h2>
                <div class="skills-grid">
                    <div class="skill-card">
                        <div class="skill-icon">🌐</div>
                        <h3>Frontend Development</h3>
                        <p>HTML, CSS, JavaScript, React, Vue</p>
                    </div>
                    <div class="skill-card">
                        <div class="skill-icon">⚙️</div>
                        <h3>Backend Development</h3>
                        <p>Node.js, Python, PHP, Databases</p>
                    </div>
                    <div class="skill-card">
                        <div class="skill-icon">📱</div>
                        <h3>Responsive Design</h3>
                        <p>Mobile-first, Cross-browser compatibility</p>
                    </div>
                </div>
            </div>
        </section>

        <!-- Projects Section -->
        <section id="projects" class="projects">
            <div class="container">
                <h2 class="section-title">Projects</h2>
                <div class="projects-grid">
                    <div class="project-card">
                        <div class="project-image"></div>
                        <div class="project-content">
                            <h3>Project One</h3>
                            <p>A modern web application built with React and Node.js</p>
                            <div class="project-links">
                                <a href="#" class="btn btn-small">Live Demo</a>
                                <a href="#" class="btn btn-small btn-secondary">GitHub</a>
                            </div>
                        </div>
                    </div>
                    <div class="project-card">
                        <div class="project-image"></div>
                        <div class="project-content">
                            <h3>Project Two</h3>
                            <p>An e-commerce website with custom CMS integration</p>
                            <div class="project-links">
                                <a href="#" class="btn btn-small">Live Demo</a>
                                <a href="#" class="btn btn-small btn-secondary">GitHub</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Contact Section -->
        <section id="contact" class="contact">
            <div class="container">
                <h2 class="section-title">Get In Touch</h2>
                <div class="contact-content">
                    <div class="contact-info">
                        <div class="contact-item">
                            <div class="contact-icon">📧</div>
                            <div>
                                <h4>Email</h4>
                                <p>your.email@example.com</p>
                            </div>
                        </div>
                        <div class="contact-item">
                            <div class="contact-icon">📱</div>
                            <div>
                                <h4>Phone</h4>
                                <p>+1 (555) 123-4567</p>
                            </div>
                        </div>
                    </div>
                    <form class="contact-form">
                        <div class="form-group">
                            <input type="text" placeholder="Your Name" required>
                        </div>
                        <div class="form-group">
                            <input type="email" placeholder="Your Email" required>
                        </div>
                        <div class="form-group">
                            <textarea placeholder="Your Message" rows="5" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Send Message</button>
                    </form>
                </div>
            </div>
        </section>

        <!-- Footer -->
        <footer class="footer">
            <div class="container">
                <p>&copy; 2024 Your Name. All rights reserved.</p>
            </div>
        </footer>
      `

      const css = `
        :root {
            --primary-color: #3b82f6;
            --secondary-color: #64748b;
            --accent-color: #f59e0b;
            --text-color: #1f2937;
            --light-bg: #f8fafc;
            --white: #ffffff;
            --shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
            line-height: 1.6;
            color: var(--text-color);
            margin: 0;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 2rem;
        }

        /* Navigation */
        .navbar {
            position: fixed;
            top: 0;
            width: 100%;
            background: var(--white);
            box-shadow: var(--shadow);
            z-index: 1000;
            padding: 1rem 0;
        }

        .navbar .container {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .nav-brand h2 {
            color: var(--primary-color);
            margin: 0;
        }

        .nav-menu {
            display: flex;
            list-style: none;
            gap: 2rem;
            margin: 0;
        }

        .nav-link {
            text-decoration: none;
            color: var(--text-color);
            font-weight: 500;
            transition: color 0.3s;
        }

        .nav-link:hover {
            color: var(--primary-color);
        }

        .hamburger {
            display: none;
            flex-direction: column;
            cursor: pointer;
        }

        .hamburger span {
            width: 25px;
            height: 3px;
            background: var(--text-color);
            margin: 3px 0;
            transition: 0.3s;
        }

        /* Hero Section */
        .hero {
            min-height: 100vh;
            display: flex;
            align-items: center;
            background: linear-gradient(135deg, var(--light-bg) 0%, var(--white) 100%);
            padding-top: 80px;
        }

        .hero-content {
            text-align: center;
            max-width: 600px;
            margin: 0 auto;
        }

        .hero-title {
            font-size: 3.5rem;
            font-weight: 700;
            margin-bottom: 1rem;
            line-height: 1.2;
        }

        .highlight {
            color: var(--primary-color);
        }

        .hero-description {
            font-size: 1.25rem;
            color: var(--secondary-color);
            margin-bottom: 2rem;
        }

        .hero-buttons {
            display: flex;
            gap: 1rem;
            justify-content: center;
            flex-wrap: wrap;
        }

        /* Buttons */
        .btn {
            display: inline-block;
            padding: 12px 24px;
            border-radius: 6px;
            text-decoration: none;
            font-weight: 600;
            text-align: center;
            transition: all 0.3s;
            border: none;
            cursor: pointer;
        }

        .btn-primary {
            background: var(--primary-color);
            color: var(--white);
        }

        .btn-primary:hover {
            background: #2563eb;
            transform: translateY(-2px);
        }

        .btn-secondary {
            background: transparent;
            color: var(--primary-color);
            border: 2px solid var(--primary-color);
        }

        .btn-secondary:hover {
            background: var(--primary-color);
            color: var(--white);
        }

        .btn-small {
            padding: 8px 16px;
            font-size: 0.875rem;
        }

        /* Sections */
        .section-title {
            text-align: center;
            font-size: 2.5rem;
            font-weight: 700;
            margin-bottom: 3rem;
            color: var(--text-color);
        }

        .about {
            padding: 5rem 0;
            background: var(--white);
        }

        .about-content {
            max-width: 800px;
            margin: 0 auto;
            text-align: center;
        }

        .about-text p {
            font-size: 1.125rem;
            margin-bottom: 1.5rem;
            color: var(--secondary-color);
        }

        /* Skills */
        .skills {
            padding: 5rem 0;
            background: var(--light-bg);
        }

        .skills-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
        }

        .skill-card {
            background: var(--white);
            padding: 2rem;
            border-radius: 12px;
            text-align: center;
            box-shadow: var(--shadow);
            transition: transform 0.3s;
        }

        .skill-card:hover {
            transform: translateY(-5px);
        }

        .skill-icon {
            font-size: 3rem;
            margin-bottom: 1rem;
        }

        .skill-card h3 {
            font-size: 1.5rem;
            margin-bottom: 1rem;
            color: var(--text-color);
        }

        .skill-card p {
            color: var(--secondary-color);
        }

        /* Projects */
        .projects {
            padding: 5rem 0;
            background: var(--white);
        }

        .projects-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
            gap: 2rem;
        }

        .project-card {
            background: var(--light-bg);
            border-radius: 12px;
            overflow: hidden;
            box-shadow: var(--shadow);
            transition: transform 0.3s;
        }

        .project-card:hover {
            transform: translateY(-5px);
        }

        .project-image {
            height: 200px;
            background: linear-gradient(45deg, var(--primary-color), var(--accent-color));
            position: relative;
        }

        .project-content {
            padding: 1.5rem;
        }

        .project-content h3 {
            font-size: 1.5rem;
            margin-bottom: 1rem;
            color: var(--text-color);
        }

        .project-content p {
            color: var(--secondary-color);
            margin-bottom: 1.5rem;
        }

        .project-links {
            display: flex;
            gap: 1rem;
        }

        /* Contact */
        .contact {
            padding: 5rem 0;
            background: var(--light-bg);
        }

        .contact-content {
            display: grid;
            grid-template-columns: 1fr 2fr;
            gap: 3rem;
            align-items: start;
        }

        .contact-item {
            display: flex;
            align-items: center;
            gap: 1rem;
            margin-bottom: 2rem;
        }

        .contact-icon {
            font-size: 1.5rem;
            width: 50px;
            height: 50px;
            background: var(--primary-color);
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .contact-item h4 {
            font-size: 1.125rem;
            margin-bottom: 0.25rem;
            color: var(--text-color);
        }

        .contact-item p {
            color: var(--secondary-color);
            margin: 0;
        }

        .contact-form {
            background: var(--white);
            padding: 2rem;
            border-radius: 12px;
            box-shadow: var(--shadow);
        }

        .form-group {
            margin-bottom: 1.5rem;
        }

        .form-group input,
        .form-group textarea {
            width: 100%;
            padding: 12px;
            border: 2px solid #e5e7eb;
            border-radius: 6px;
            font-size: 1rem;
            transition: border-color 0.3s;
        }

        .form-group input:focus,
        .form-group textarea:focus {
            outline: none;
            border-color: var(--primary-color);
        }

        /* Footer */
        .footer {
            background: var(--text-color);
            color: var(--white);
            text-align: center;
            padding: 2rem 0;
        }

        /* Responsive */
        @media (max-width: 768px) {
            .hamburger {
                display: flex;
            }

            .nav-menu {
                display: none;
            }

            .hero-title {
                font-size: 2.5rem;
            }

            .hero-buttons {
                flex-direction: column;
                align-items: center;
            }

            .contact-content {
                grid-template-columns: 1fr;
            }

            .container {
                padding: 0 1rem;
            }
        }

        @media (max-width: 480px) {
            .hero-title {
                font-size: 2rem;
            }

            .section-title {
                font-size: 2rem;
            }
        }
      `

      const js = `
        // Smooth scrolling for navigation links
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({
                        behavior: 'smooth'
                    });
                }
            });
        });

        // Mobile navigation toggle
        const hamburger = document.querySelector('.hamburger');
        const navMenu = document.querySelector('.nav-menu');

        hamburger.addEventListener('click', () => {
            hamburger.classList.toggle('active');
            navMenu.classList.toggle('active');
        });

        // Close mobile menu when clicking on a link
        document.querySelectorAll('.nav-link').forEach(n => n.addEventListener('click', () => {
            hamburger.classList.remove('active');
            navMenu.classList.remove('active');
        }));

        // Contact form handling
        const contactForm = document.querySelector('.contact-form');
        contactForm.addEventListener('submit', function(e) {
            e.preventDefault();
            
            // Get form data
            const formData = new FormData(this);
            const name = this.querySelector('input[type="text"]').value;
            const email = this.querySelector('input[type="email"]').value;
            const message = this.querySelector('textarea').value;
            
            // Simple validation
            if (name && email && message) {
                alert('Thank you for your message! I will get back to you soon.');
                this.reset();
            } else {
                alert('Please fill in all fields.');
            }
        });

        // Navbar background change on scroll
        window.addEventListener('scroll', () => {
            const navbar = document.querySelector('.navbar');
            if (window.scrollY > 50) {
                navbar.style.background = 'rgba(255, 255, 255, 0.95)';
                navbar.style.backdropFilter = 'blur(10px)';
            } else {
                navbar.style.background = 'var(--white)';
                navbar.style.backdropFilter = 'none';
            }
        });

        // Add CSS for mobile menu
        const style = document.createElement('style');
        style.textContent = \`
            @media (max-width: 768px) {
                .nav-menu {
                    position: fixed;
                    left: -100%;
                    top: 70px;
                    flex-direction: column;
                    background-color: var(--white);
                    width: 100%;
                    text-align: center;
                    transition: 0.3s;
                    box-shadow: var(--shadow);
                    padding: 2rem 0;
                }

                .nav-menu.active {
                    left: 0;
                }

                .hamburger.active span:nth-child(2) {
                    opacity: 0;
                }

                .hamburger.active span:nth-child(1) {
                    transform: translateY(8px) rotate(45deg);
                }

                .hamburger.active span:nth-child(3) {
                    transform: translateY(-8px) rotate(-45deg);
                }
            }
        \`;
        document.head.appendChild(style);
      `

      return generateSingleFileProject(html, css, js, {
        title: 'Professional Portfolio',
        description: 'A modern, responsive portfolio website showcasing skills and projects'
      })
    }
  },
  
  {
    name: 'Landing Page',
    description: 'A conversion-focused landing page for products or services',
    generateContent: (customContent = '') => {
      // Similar structure for landing page...
      return generateSingleFileProject('', '', '', {
        title: 'Landing Page',
        description: 'A high-converting landing page'
      })
    }
  }
]