import assert from "node:assert/strict"
import { describe, it } from "node:test"
import fs from "node:fs"
import path from "node:path"
import sharp from "sharp"

const root = process.cwd()
const source = (rel: string) => fs.readFileSync(path.join(root, rel), "utf8")

const IGNORED_DIRS = new Set(["node_modules", "siraGPT", "upstream", ".next", ".test-dist"])

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (IGNORED_DIRS.has(entry.name)) continue
    const abs = path.join(dir, entry.name)
    if (entry.isDirectory()) walk(abs, out)
    else if (/\.(tsx|ts|jsx|js)$/.test(entry.name)) out.push(abs)
  }
  return out
}

describe("Clover brand (four-leaf clover mark + green accent)", () => {
  it("ships the clover SVG for documents, and the Sira mark as favicon, PWA icons and manifest (Luis, 2026-10-09)", () => {
    const svg = source("public/brand/clover.svg")
    assert.match(svg, /fill="currentColor"/)
    assert.match(svg, /viewBox="0 0 512 512"/)
    // Browser tab + PWA icons are the eight-arm Sira mark on a white tile; the clover and atom PNGs are gone.
    const icon = source("public/icon.svg")
    assert.doesNotMatch(icon, /<image|#2E7D32|A170 62|rotate\(/i)
    assert.equal((icon.match(/<line /g) || []).length, 8, "eight arms")
    assert.equal((icon.match(/<circle /g) || []).length, 9, "eight dots + the centre")
    assert.match(icon, /stroke-linecap="round"/)
    for (const rel of ["public/favicon.ico", "public/sira-gpt-192.png", "public/sira-gpt-512.png", "public/sira-gpt-180.png", "public/apple-touch-icon.png", "public/brand/sira-maskable-512.png", "public/brand/sira-mark.svg"]) {
      assert.ok(fs.existsSync(path.join(root, rel)), `${rel} exists`)
    }
    for (const rel of ["public/brand/clover-maskable-512.png", "public/brand/clover-512.png", "public/brand/atom-maskable-512.png", "public/brand/atom.svg"]) {
      assert.ok(!fs.existsSync(path.join(root, rel)), `${rel} is gone`)
    }
    const manifest = JSON.parse(source("public/manifest.webmanifest"))
    assert.equal(manifest.theme_color, "#ffffff")
    assert.equal(manifest.background_color, "#ffffff")
    assert.ok(manifest.icons.some((i: { src: string; purpose?: string }) => i.src === "/brand/sira-maskable-512.png" && i.purpose === "maskable"))
    assert.ok(!manifest.icons.some((i: { src: string }) => /clover|atom/.test(i.src)))
    // Cache-busted icon URLs so browsers drop the cached atom favicon.
    const layout = source("app/layout.tsx")
    assert.match(layout, /\{ url: "\/favicon\.ico\?v=sira", sizes: "any" \}/)
    assert.match(layout, /\/sira-gpt-180\.png\?v=sira/)
    assert.doesNotMatch(layout, /\?v=atom/)
    assert.match(source("public/sw.js"), /'\/brand\/sira-mark\.svg'/)
    assert.doesNotMatch(source("public/sw.js"), /clover|atom\.svg/)
  })

  // Every raster outside the web app is generated from the same motion model by
  // `npm run brand:assets` (scripts/generate-brand-assets.cjs): social cards,
  // Capacitor Android/iOS icons + splashes, the Electron desktop icon set and
  // the browser-extension icons. These used to carry the clover, the knot or
  // the Capacitor default long after the in-app mark changed.
  it("ships the official mark on the social cards, the native app icons, the desktop icons and the extension (generated by scripts/generate-brand-assets.cjs)", () => {
    const generator = source("scripts/generate-brand-assets.cjs")
    assert.match(generator, /lib\/brand\/sira-motion\.ts/, "renders from the motion model, never a traced raster")
    assert.match(generator, /ts\.transpileModule\(/)
    for (const surface of ["web", "social", "android", "ios", "desktop", "extension"]) {
      assert.match(generator, new RegExp(`async function ${surface}\\(\\)`), `surface ${surface}`)
    }
    assert.match(source("package.json"), /"brand:assets": "node scripts\/generate-brand-assets\.cjs"/)
    const pngSize = (rel: string) => {
      const buf = fs.readFileSync(path.join(root, rel))
      assert.equal(buf.toString("latin1", 1, 4), "PNG", `${rel} is a PNG`)
      return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20), alpha: buf[25] === 6 }
    }
    assert.deepEqual(pngSize("public/opengraph-image.png"), { width: 1200, height: 630, alpha: true })
    // Apple touch icons are opaque and full-bleed: iOS composites alpha on black under its own mask.
    assert.deepEqual(pngSize("public/apple-touch-icon.png"), { width: 180, height: 180, alpha: false })
    assert.ok(fs.readFileSync(path.join(root, "public/apple-touch-icon.png")).equals(fs.readFileSync(path.join(root, "public/sira-gpt-180.png"))), "sira-gpt-180 is the same opaque icon")
    assert.deepEqual(pngSize("public/sira-gpt-512.png"), { width: 512, height: 512, alpha: true })
    // Google Play listing icon: opaque full-bleed square, separate from the rounded desktop icon.
    assert.deepEqual(pngSize("docs/store-submission/assets/android/play-icon-512.png"), { width: 512, height: 512, alpha: false })
    const storeManifest = JSON.parse(source("docs/store-submission/native-store-assets.json"))
    const playIcon = storeManifest.platforms.android.requiredAssets.find((a: { id: string }) => a.id === "play-high-res-icon")
    assert.deepEqual({ path: playIcon.path, allowAlpha: playIcon.allowAlpha }, { path: "docs/store-submission/assets/android/play-icon-512.png", allowAlpha: false })
    assert.ok(fs.readFileSync(path.join(root, "public/opengraph-image.png")).equals(fs.readFileSync(path.join(root, "public/twitter-image.png"))), "one card for both networks")
    assert.deepEqual(pngSize("android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"), { width: 192, height: 192, alpha: true })
    assert.deepEqual(pngSize("android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png"), { width: 432, height: 432, alpha: true })
    assert.deepEqual(pngSize("android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png"), { width: 48, height: 48, alpha: true })
    assert.deepEqual(pngSize("android/app/src/main/res/drawable-port-xxxhdpi/splash.png"), { width: 1280, height: 1920, alpha: true })
    // App Store icons must be opaque (colour type 2, no alpha channel).
    assert.deepEqual(pngSize("ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png"), { width: 1024, height: 1024, alpha: false })
    assert.deepEqual(pngSize("ios/App/App/Assets.xcassets/Splash.imageset/splash-2732x2732.png"), { width: 2732, height: 2732, alpha: false })
    assert.deepEqual(pngSize("apps/desktop/assets/icon.png"), { width: 512, height: 512, alpha: true })
    assert.deepEqual(pngSize("extension/icons/icon-128.png"), { width: 128, height: 128, alpha: true })
    const icns = fs.readFileSync(path.join(root, "apps/desktop/assets/icon.icns"))
    assert.equal(icns.toString("latin1", 0, 4), "icns")
    assert.equal(icns.readUInt32BE(4), icns.length, "icns length header matches the file")
    const icnsFloor = storeManifest.platforms.macos.requiredAssets.find((a: { id: string }) => a.id === "macos-icns-icon").minBytes
    assert.ok(icns.length >= icnsFloor, `store readiness floor for icon.icns (${icns.length} < ${icnsFloor})`)
    const ico = fs.readFileSync(path.join(root, "apps/desktop/assets/icon.ico"))
    assert.deepEqual([ico.readUInt16LE(0), ico.readUInt16LE(2), ico.readUInt16LE(4)], [0, 1, 7], "ICO with 7 entries (16…256)")
    assert.ok(ico.length >= 50_000, "store readiness floor for icon.ico")
    const favicon = fs.readFileSync(path.join(root, "public/favicon.ico"))
    assert.deepEqual([favicon.readUInt16LE(2), favicon.readUInt16LE(4)], [1, 3], "favicon: 16/32/48")
    // The service worker precache list changed (atom.svg → sira-mark.svg), so its schema version moved on.
    assert.match(source("public/sw.js"), /const SCHEMA_VERSION = 'sira-v4'/)
  })

  // Headers prove the containers; this proves the mark is actually drawn where
  // it belongs — ink in the middle, white or transparent at the corners.
  it("draws the ink mark in the middle of every generated raster, with white or transparent corners", async () => {
    const px = async (rel: string, x: number, y: number) => {
      const { data, info } = await sharp(path.join(root, rel)).ensureAlpha().raw().toBuffer({ resolveWithObject: true })
      const i = (y * info.width + x) * 4
      return [data[i], data[i + 1], data[i + 2], data[i + 3]]
    }
    const INK = [10, 10, 10, 255]
    const WHITE = [255, 255, 255, 255]
    assert.deepEqual(await px("public/opengraph-image.png", 600, 253), INK, "social card: the mark's centre is ink")
    assert.deepEqual(await px("public/opengraph-image.png", 10, 10), WHITE, "social card: white background")
    assert.deepEqual(await px("public/apple-touch-icon.png", 0, 0), WHITE, "apple icon: opaque white corner (no black corners on iOS)")
    assert.deepEqual(await px("public/apple-touch-icon.png", 90, 90), INK)
    assert.equal((await px("public/sira-gpt-512.png", 0, 0))[3], 0, "PWA tile: transparent rounded corner")
    assert.deepEqual(await px("public/sira-gpt-512.png", 256, 256), INK)
    assert.deepEqual(await px("public/brand/sira-maskable-512.png", 0, 0), WHITE, "maskable: full-bleed white")
    assert.equal((await px("android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png", 0, 0))[3], 0, "adaptive foreground: transparent outside the mark")
    assert.deepEqual(await px("android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png", 216, 216), INK)
    assert.deepEqual(await px("ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png", 0, 0), WHITE, "App Store icon: opaque white corner")
    assert.deepEqual(await px("ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png", 512, 512), INK)
    assert.deepEqual(await px("docs/store-submission/assets/android/play-icon-512.png", 0, 0), WHITE, "Play icon: opaque full-bleed")
    assert.equal((await px("apps/desktop/assets/icon.png", 0, 0))[3], 0, "desktop icon: rounded tile with transparent corner")
    assert.deepEqual(await px("apps/desktop/assets/icon.png", 256, 256), INK)
    assert.deepEqual(await px("extension/icons/icon-128.png", 64, 64), INK)
  })

  it("keeps CloverMark for the document assets and uses the Sira mark for every in-app logo render", () => {
    const mark = source("components/brand/clover-mark.tsx")
    assert.match(mark, /export function CloverMark/)
    assert.match(mark, /export function CloverBadge/)
    assert.match(mark, /fill="currentColor"/)
    assert.match(mark, /var\(--clover-vein, #fff\)/)
    assert.match(source("components/brand/index.ts"), /export \{ CloverMark, CloverBadge \} from "\.\/clover-mark"/)
    assert.match(source("components/brand/index.ts"), /export \{ SiraMark \} from "\.\/sira-mark"/)
    assert.doesNotMatch(source("components/brand/index.ts"), /knot-mark|atom-mark/)
    // Luis (2026-10-09): the official brand mark is the eight-arm Sira mark —
    // a solid centre with eight straight arms (north, clockwise every 45°)
    // ending in solid dots, one ink in currentColor («tinta»). Its geometry
    // is shared with the animated «Pensando» glyph (lib/brand/sira-motion.ts)
    // and it is pure vector — never a traced raster.
    const siraMark = source("components/brand/sira-mark.tsx")
    assert.match(siraMark, /export function SiraMark/)
    assert.match(siraMark, /data-brand="sira"/)
    assert.match(siraMark, /import \{ logoGeometryFor, openFrame, type SiraGeometry \} from "@\/lib\/brand\/sira-motion"/)
    assert.match(siraMark, /<g stroke="currentColor" strokeWidth=\{geometry\.stroke\} strokeLinecap="round">/)
    assert.match(siraMark, /<g fill="currentColor">/)
    assert.match(siraMark, /<circle cx=\{frame\.centre\} cy=\{frame\.centre\} r=\{frame\.centerRadius\} \/>/)
    assert.doesNotMatch(siraMark, /<image|data:image|A170 62|rotate\(/)
    const motion = source("lib/brand/sira-motion.ts")
    assert.match(motion, /export const LOGO_GEOMETRY: SiraGeometry = Object\.freeze\(\{ size: 400, reach: 163, center: 48, seed: 38, tip: 37, stroke: 17 \}\)/)
    assert.match(motion, /export const SIRA_TIMING: SiraTiming = Object\.freeze\(\{ cycle: 2000, start: 0, duration: 970, close: 1000, stagger: 10 \}\)/)
    assert.match(motion, /export const ARM_RANKS: readonly number\[\] = Object\.freeze\(\[0, 2, 1, 3, 0, 2, 1, 3\]\)/)
    const asset = source("public/brand/sira-mark.svg")
    assert.match(asset, /viewBox="0 0 400 400"/)
    assert.match(asset, /stroke="currentColor" stroke-width="17" stroke-linecap="round"/)
    assert.equal((asset.match(/<line /g) || []).length, 8)
    assert.equal((asset.match(/<circle /g) || []).length, 9)
    assert.match(asset, /<circle cx="200" cy="200" r="48"\/>/)
    // The knot (2026-10-01) and the atom (2026-10-02) are gone: one in-app brand mark only.
    for (const rel of ["components/brand/knot-mark.tsx", "public/brand/knot.svg", "components/brand/atom-mark.tsx", "public/brand/atom.svg"]) {
      assert.ok(!fs.existsSync(path.join(root, rel)), `${rel} is gone`)
    }
    const css = source("app/globals.css")
    assert.doesNotMatch(css, /--knot-gap/)
    for (const rel of [
      "components/BrandLogo.tsx",
      "components/app-sidebar.tsx",
      "components/PWAInstallPrompt.tsx",
      "components/BrandCycle.tsx",
      "app/auth/login/page.tsx",
      "app/auth/register/page.tsx",
      "app/auth/forgot-password/page.tsx",
      "app/auth/reset-password/page.tsx",
      "app/auth/reset/[token]/page.tsx",
    ]) {
      const src = source(rel)
      assert.match(src, /import \{ SiraMark \} from "@\/components\/brand"/, `${rel} imports SiraMark`)
      assert.match(src, /<SiraMark/, `${rel} renders SiraMark`)
      assert.doesNotMatch(src, /<CloverMark|KnotMark|AtomMark/, `${rel} renders neither the clover, the knot nor the atom`)
    }
  })

  // Luis (2026-09-29): the interface is black & white — the in-app brand ink
  // is near-black on light and near-white on dark (the PWA icon, emails and
  // generated documents keep the clover green asset).
  it("uses a monochrome ink as the in-app brand accent in both themes; the thinking mark is ink only (red on error)", () => {
    const css = source("app/globals.css")
    assert.match(css, /--brand: #0A0A0A;/)
    assert.match(css, /--brand: #FAFAFA;/)
    // The thinking glyph — the Sira mark in motion — is the foreground (black on light, white on dark), in both
    // themes (Luis, 2026-10-03: monochrome; the electron colour tokens of 2026-10-02 are gone). Red only on error.
    assert.equal((css.match(/--think-accent: hsl\(var\(--foreground\)\);/g) || []).length, 2)
    assert.doesNotMatch(css, /--think-accent: #(2E7D32|66BB6A);/i)
    assert.doesNotMatch(css, /--think-electron-[abc]:/)
    assert.match(css, /--clover-vein: #ffffff;/)
    assert.match(css, /--accent-violet: 0 0% 4%;/)
    assert.match(css, /--accent-violet: 0 0% 96%;/)
    assert.doesNotMatch(css, /--brand: #(7c5cff|5b4dff);/i)
    assert.match(source("lib/thinking-loaders.ts"), /export const CLAUDE_THINK_ACCENT = "currentColor"/)
    // The thinking glyph is the ThinkingCore (the Sira mark in motion, not the clover), drawn in the think accent.
    const asterisk = source("components/claude-asterisk.tsx")
    assert.match(asterisk, /data-brand="thinking-core"/)
    assert.doesNotMatch(asterisk, /data-brand="clover"/)
    assert.match(asterisk, /export function ClaudeAsterisk/)
    const core = source("components/brand/thinking-core.tsx")
    assert.match(core, /var\(--think-accent, \$\{CLAUDE_THINK_ACCENT\}\)/)
    assert.match(core, /data-brand-geometry="sira"/)
    assert.doesNotMatch(core, /--think-electron-/)
    assert.match(core, /tone = "default"/)
  })

  it("leaves no raster sira-gpt.png logo render under app/ and components/", () => {
    const offenders: string[] = []
    for (const dir of ["app", "components"]) {
      for (const file of walk(path.join(root, dir))) {
        const src = fs.readFileSync(file, "utf8")
        if (/<(Image|img)\b[^>]*src=["']\/sira-gpt\.png["']/.test(src) || /<(Image|img)\b[^>]*\n[^>]*src=["']\/sira-gpt\.png["']/.test(src)) {
          offenders.push(path.relative(root, file))
        }
      }
    }
    assert.deepEqual(offenders, [])
  })

  it("brands transactional emails and generated documents in clover green", () => {
    const email = source("backend/src/services/email.js")
    assert.doesNotMatch(email, /#667eea/i)
    assert.doesNotMatch(email, /#3498db/i)
    assert.match(email, /linear-gradient\(135deg, #2E7D32 0%, #1B5E20 100%\)/)
    const pipeline = source("backend/src/services/document-pipeline/advanced-document-pipeline.js")
    assert.match(pipeline, /buildCoverAccentPng\(accent = '2E7D32', accent2 = '66BB6A'\)/)
  })
})
