import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const companySource = readFileSync("components/code/agent-company-panel.tsx", "utf8")
const resourcesSource = readFileSync("components/code/company-resources-surface.tsx", "utf8")
const codeChatSource = readFileSync("components/code/ai-code-chat-panel.tsx", "utf8")
const workspaceSource = readFileSync("lib/code-workspace-context.tsx", "utf8")
const previewSource = readFileSync("components/code/preview-pane.tsx", "utf8")
const socialApiSource = readFileSync("lib/company-social-api.ts", "utf8")
const resourceKeysSource = readFileSync("lib/company-resource-keys.ts", "utf8")
const codexApiSource = readFileSync("lib/codex/codex-api.ts", "utf8")
const postPageSource = readFileSync("app/post/page.tsx", "utf8")

test("company navigation renders operational surfaces inside the preview slot", () => {
  assert.match(previewSource, /data-testid="agent-company-preview-slot"/)
  assert.match(companySource, /createPortal\([\s\S]*?<CompanyPreviewSurface/)
  assert.match(companySource, /data-testid="agent-company-preview-surface"/)
  assert.match(companySource, /data-company-view=\{view\}/)
  assert.match(companySource, /activePreviewView === "dashboard"/)
  assert.match(companySource, /activePreviewView === "control"/)
  assert.match(companySource, /activePreviewView === "files"/)
  assert.match(companySource, /activePreviewView === "resources"/)
})

test("company files and resources expose real workspace and social operations", () => {
  assert.match(companySource, /testId="company-files-surface"/)
  assert.match(companySource, /buildCompanyAgentFileArtifacts/)
  assert.match(companySource, /workers=\{officeModel\.workers\}/)
  assert.match(companySource, /data-testid="company-agent-files-group"/)
  assert.match(companySource, /data-testid="company-mission-evidence-ledger"/)
  assert.match(companySource, /codexApi\.getMissionEvidence/)
  assert.match(companySource, /codexApi\.reviewMissionEvidence/)
  assert.match(companySource, /codexApi\.createActivityReport/)
  assert.match(companySource, /No se envió ningún correo/)
  assert.match(companySource, /<CompanyResourcesSurface/)
  assert.match(resourcesSource, /data-testid="company-resources-surface"/)
  assert.match(resourcesSource, /codexApi\.getCompanyResources/)
  assert.match(resourcesSource, /codexApi\.updateCompanyResources/)
  assert.match(resourcesSource, /companySocialResourceKey\(provider\)/)
  assert.match(resourceKeysSource, /social:v2:/)
  assert.match(resourceKeysSource, /encodeURIComponent\(connectionId\)/)
  assert.match(resourceKeysSource, /encodeURIComponent\(accountId\)/)
  assert.match(resourceKeysSource, /isLegacyCompanySocialResourceKey/)
  assert.doesNotMatch(resourcesSource, /const key = `social:\$\{provider\.platform\}`/)
  assert.match(resourcesSource, /Gestiona:/)
  assert.match(resourcesSource, /Quitar de esta empresa/)
  assert.doesNotMatch(resourcesSource, /onDisconnectSocial/)
  assert.doesNotMatch(resourcesSource, /countBias/)
  assert.match(companySource, /marketingAllowedPlatforms/)
  assert.match(companySource, /assignedCompanySocialPlatforms/)
  assert.match(companySource, /"marketing",/)
  assert.doesNotMatch(companySource, /marketingDepartmentId/)
  assert.match(companySource, /socialLoadGenerationRef/)
  assert.match(companySource, /draftScope !== socialScopeRef\.current/)
  assert.match(companySource, /codexProjectId=\{associatedCodexProjectId\}/)
  assert.match(companySource, /companySocialApi\.queueTextPost/)
  assert.match(companySource, /companySocialApi\.publishNow/)
  assert.match(resourcesSource, /clearLocalResourceState/)
  assert.match(resourcesSource, /mergeResourceStates/)
  assert.match(resourcesSource, /departments\.find\(\(d\) => d\.id === "marketing"\)/)
  assert.match(resourcesSource, /data-testid="company-resources-load-error"/)
  assert.match(resourcesSource, /No se guardará ningún cambio/)
  assert.match(resourcesSource, /onAssignConnectorToCompany/)
  assert.match(companySource, /codexApi\.addCompanyConnector/)
  assert.match(companySource, /availableConnectorAccountIds=/)
  assert.match(companySource, /associationState\?\.association\?\.connectors\.map/)
  assert.match(resourcesSource, /availableConnectorAccountIds\.has/)
  assert.match(resourcesSource, /isCompanyResourceActive/)
  assert.match(resourcesSource, /Habilitar en empresa/)
  assert.match(resourcesSource, /await commitResourceState/)
  assert.match(resourcesSource, /persistCompanyResourcesConfirmed/)
  assert.match(resourcesSource, /resourceStateUnknown/)
  assert.match(resourcesSource, /Availability is not an executable permission/)
  assert.match(resourcesSource, /authoritative department grant/)
  assert.match(resourcesSource, /la cuenta sigue disponible para la empresa/)
  assert.match(resourcesSource, /data-testid="company-connectors-load-error"/)
  assert.match(resourcesSource, /Las acciones de conexión están bloqueadas/)
  assert.match(resourcesSource, /aria-label="Buscar apps e integraciones"/)
  assert.match(resourcesSource, /aria-pressed=\{category === id\}/)
  assert.match(resourcesSource, /"Reconectar"/)
  assert.match(resourcesSource, /\/icons\/gmail\.svg/)
  assert.match(companySource, /marketingPublishingPlatforms/)
  assert.match(companySource, /result\.action !== "published"/)
  assert.match(companySource, /onPatchPlatform=\{patchPlatform\}/)
  assert.match(codexApiSource, /expectedRevision: resources\.revision/)
  assert.match(codexApiSource, /addCompanyConnector/)
  assert.match(socialApiSource, /request<\{ post: CompanySocialPost \}>\("\/queue"/)
  assert.match(socialApiSource, /encodeURIComponent\(postId\).*publish-now/)
})

test("resource removal revokes only the department grant and preserves connector availability", () => {
  const start = resourcesSource.indexOf("const removeResource")
  const end = resourcesSource.indexOf("const enableConnectorForCompany", start)
  const removeSource = resourcesSource.slice(start, end)
  assert.ok(start >= 0 && end > start)
  assert.match(removeSource, /await commitResourceState/)
  assert.doesNotMatch(removeSource, /removeCompanyConnector/)
  assert.match(removeSource, /cuenta sigue disponible/)
})

test("connector grants remain fail-closed until company availability is confirmed", () => {
  const assignStart = resourcesSource.indexOf("const assignResource")
  const assignEnd = resourcesSource.indexOf("const togglePin", assignStart)
  const assignSource = resourcesSource.slice(assignStart, assignEnd)
  const enableStart = resourcesSource.indexOf("const enableConnectorForCompany")
  const enableEnd = resourcesSource.indexOf("const handlePrimary", enableStart)
  const enableSource = resourcesSource.slice(enableStart, enableEnd)
  const hydrateStart = resourcesSource.indexOf("const hydrate = async")
  const hydrateEnd = resourcesSource.indexOf("const pinSet", hydrateStart)
  const hydrateSource = resourcesSource.slice(hydrateStart, hydrateEnd)

  assert.ok(assignStart >= 0 && assignEnd > assignStart)
  assert.ok(enableStart >= 0 && enableEnd > enableStart)
  assert.ok(hydrateStart >= 0 && hydrateEnd > hydrateStart)
  assert.ok(
    assignSource.indexOf("onAssignConnectorToCompany(item.connector)")
      < assignSource.indexOf("await commitResourceState"),
    "connector availability must be established before a new department grant",
  )
  assert.match(enableSource, /await onAssignConnectorToCompany\(item\.connector\)/)
  assert.doesNotMatch(enableSource, /commitResourceState/)
  assert.match(hydrateSource, /invalidConnectorKeys/)
  assert.match(hydrateSource, /await onAssignConnectorToCompany\(connector\)/)
  assert.doesNotMatch(hydrateSource, /status !== "connected"/)
  assert.match(resourcesSource, /!item\.availableToCompany/)
})

test("automatic post series remain scoped to the active company and literal Marketing resources", () => {
  assert.match(postPageSource, /getActiveCodexProject/)
  assert.match(postPageSource, /codexApi\.getCompanyResources\(activeWorkspaceId\)/)
  assert.match(postPageSource, /companySocialResourceKeyForConnection/)
  assert.match(postPageSource, /resources\?\.assignments\?\.\[resourceKey\] === "marketing"/)
  assert.match(postPageSource, /workspaceId,/)
  assert.match(postPageSource, /social-posts\?workspaceId=/)
  assert.match(postPageSource, /loadGenerationRef/)
  assert.match(postPageSource, /loadAbortRef/)
  assert.match(postPageSource, /companySocialApi\.legacySummary\(activeWorkspaceId\)/)
  assert.match(postPageSource, /companySocialApi\.assignLegacyPosts\(workspaceId\)/)
  assert.match(postPageSource, /Publicaciones anteriores sin empresa/)
  assert.match(postPageSource, /ninguna se publicará automáticamente/i)
  assert.match(postPageSource, /legacyLoadError/)
  assert.match(postPageSource, /No se realizará ninguna asignación/)
  assert.match(postPageSource, /window\.confirm/)
  assert.match(socialApiSource, /\/legacy\?workspaceId=/)
  assert.match(socialApiSource, /request<CompanySocialLegacyAssignment>\("\/legacy\/assign"/)
  assert.match(socialApiSource, /confirm: true/)
  assert.match(postPageSource, /connect\/\$\{network\.id\}\?redirect=1/)
  assert.doesNotMatch(postPageSource, /id: "instagram"/)
  assert.doesNotMatch(postPageSource, /id: "youtube"/)
})

test("company dashboard renders the evidence-grounded operating diagnosis", () => {
  assert.match(companySource, /proactiveResult\.value\.company/)
  assert.match(companySource, /data-testid="company-operating-diagnosis"/)
  assert.match(companySource, /companyContext\.readiness\.score/)
  assert.match(companySource, /companyContext\.profile\.mission/)
  assert.match(companySource, /companyContext\.profile\.vision/)
  assert.match(companySource, /area\.status === "ready" \? area\.evidence : area\.action/)
  assert.match(companySource, /data-testid="company-mission-portfolio"/)
  assert.match(companySource, /companyContext\.portfolio\.missions/)
  assert.match(companySource, /mission\.departmentName/)
  assert.match(companySource, /mission\.nextAction/)
  assert.match(companySource, /data-testid="company-okr-portfolio"/)
  assert.match(companySource, /companyContext\.okrs/)
  assert.match(companySource, /objective\.keyResults/)
  assert.match(codexApiSource, /getCompanyOkrs/)
  assert.match(codexApiSource, /reviewCompanyOkrs/)
  assert.match(codexApiSource, /reprioritizeCompanyOkrs/)
})

test("company runtime identity is durable and legacy browser links are confirmation hints only", () => {
  assert.match(codexApiSource, /getCompanyAssociation/)
  assert.match(codexApiSource, /associateCompany/)
  assert.match(codexApiSource, /assignCompanyConnectors/)
  assert.match(companySource, /codexApi\.addCompanyConnector/)
  assert.match(companySource, /await codexApi\.getCompanyAssociation\(requestedCompanyId\)/)
  assert.match(companySource, /shouldAcceptCompanyAssociationResponse/)
  assert.match(companySource, /associatedCodexProjectIdForCompany/)
  assert.match(companySource, /await codexApi\.associateCompany\(/)
  assert.match(companySource, /data-testid="company-association-wizard"/)
  assert.match(companySource, /No se aplican asociaciones automáticas/)
  assert.match(companySource, /connector\.scopes\?\.length \|\| 0/)
  assert.match(companySource, /durableState\.company\.organizationId/)
  assert.match(companySource, /legacyHint/)
  assert.match(companySource, /setActiveCodexProject\(null\)/)
  assert.match(workspaceSource, /durable Project ↔ CodexProject association/)
  assert.match(codeChatSource, /durableCompanyCodexProjectId/)
  assert.match(codeChatSource, /companyOrganizationId = association\.company\.organizationId/)
  assert.match(codeChatSource, /createProject\(title, text, companyOrganizationId\)/)
  assert.match(codeChatSource, /company_association_required/)
  assert.match(codeChatSource, /codexApi\.associateCompany\(/)
})
