'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '../..');
const compose = fs.readFileSync(path.join(ROOT, 'docker-compose.prod.yml'), 'utf8');
const envExample = fs.readFileSync(path.join(ROOT, '.env.example'), 'utf8');
const workerDockerfile = fs.readFileSync(path.join(ROOT, 'scripts/runsc-sandbox-worker.Dockerfile'), 'utf8');
const controllerDockerfile = fs.readFileSync(path.join(ROOT, 'scripts/runsc-sandbox-controller.Dockerfile'), 'utf8');
const controller = fs.readFileSync(path.join(ROOT, 'scripts/runsc-sandbox-controller.js'), 'utf8');
const dockerApi = fs.readFileSync(path.join(ROOT, 'scripts/runsc-sandbox-docker-api.js'), 'utf8');
const utils = fs.readFileSync(path.join(ROOT, 'scripts/runsc-sandbox-controller-utils.js'), 'utf8');
const activityStore = fs.readFileSync(path.join(ROOT, 'scripts/runsc-sandbox-activity-store.js'), 'utf8');
const workflow = fs.readFileSync(path.join(ROOT, '.github/workflows/runsc-sandbox-provider-smoke.yml'), 'utf8');
const smoke = fs.readFileSync(path.join(ROOT, 'scripts/runsc-sandbox-controller-smoke.mjs'), 'utf8');
const pkg = require('../package.json');

function serviceBlock(name, nextName) {
  const start = compose.indexOf(`  ${name}:`);
  assert.notEqual(start, -1, `missing ${name} service`);
  const end = nextName ? compose.indexOf(`  ${nextName}:`, start + 1) : compose.indexOf('\nvolumes:', start);
  return compose.slice(start, end === -1 ? compose.length : end);
}

test('only the profile-gated controller mounts Docker socket; backend and workers never do', () => {
  const controllerBlock = serviceBlock('runsc-sandbox-controller');
  const backend = serviceBlock('backend', 'frontend');
  const runner = serviceBlock('runner', 'backend');
  assert.match(controllerBlock, /profiles:\s*\["runsc-sandbox"\]/);
  assert.match(controllerBlock, /\/var\/run\/docker\.sock:\/var\/run\/docker\.sock:ro/);
  assert.doesNotMatch(backend, /docker\.sock/);
  assert.doesNotMatch(runner, /docker\.sock/);
  assert.match(controllerBlock, /user:\s*"65532:65532"/);
  assert.match(controllerBlock, /cap_drop:\s*\n\s*- ALL/);
  assert.match(controllerBlock, /no-new-privileges:true/);
  assert.match(controllerBlock, /127\.0\.0\.1:4098:4098/);
  assert.match(controllerBlock, /networks:\s*\n\s*- sandbox_controller/);
  assert.match(controllerBlock, /runsc_controller_state:\/var\/lib\/sira-runsc-controller/);
});

test('runsc provider remains off, non-public, and secretless by default', () => {
  const backend = serviceBlock('backend', 'frontend');
  assert.match(backend, /CODEX_SANDBOX_PROVIDER:\s*\$\{CODEX_SANDBOX_PROVIDER:-shared-runner\}/);
  assert.match(backend, /CODEX_RUNSC_SANDBOX_ENABLED:\s*\$\{CODEX_RUNSC_SANDBOX_ENABLED:-false\}/);
  assert.match(backend, /CODEX_RUNSC_CONTROLLER_URL:\s*\$\{CODEX_RUNSC_CONTROLLER_URL:-http:\/\/runsc-sandbox-controller:4098\}/);
  assert.match(envExample, /CODEX_RUNSC_SANDBOX_ENABLED=false/);
  assert.match(envExample, /CODEX_RUNSC_CONTROLLER_URL=http:\/\/127\.0\.0\.1:4098/);
  assert.match(backend, /CODEX_AGENT_OPEN_TO_ALL:\s*\$\{CODEX_AGENT_OPEN_TO_ALL:-false\}/);
  assert.match(utils, /publicMultiTenant:\s*false,\s*secretRefs:\s*false/);
  assert.doesNotMatch(utils, /DATABASE_URL=/);
});

test('sandbox topology is generated by Docker API without a host shell, bind, or published port', () => {
  assert.doesNotMatch(controller, /node:child_process|require\(['"]child_process/);
  assert.doesNotMatch(dockerApi, /node:child_process|require\(['"]child_process/);
  assert.match(dockerApi, /socketPath:\s*this\.socketPath/);
  assert.match(utils, /Runtime:\s*config\.runtime/);
  assert.match(utils, /User:\s*'10001:10001'/);
  assert.match(utils, /ReadonlyRootfs:\s*true/);
  assert.match(utils, /CapDrop:\s*\['ALL'\]/);
  assert.match(utils, /SecurityOpt:\s*\['no-new-privileges:true'\]/);
  assert.match(utils, /PortBindings:\s*\{\}/);
  assert.match(utils, /PublishAllPorts:\s*false/);
  assert.match(utils, /Binds:\s*\[\]/);
  assert.match(utils, /Internal:\s*true/);
  assert.match(utils, /Attachable:\s*false/);
  assert.match(utils, /gateway_mode_ipv4':\s*'isolated'/);
  assert.match(utils, /workspace volume ownership does not match/);
  assert.match(utils, /sandbox network contains another workload/);
});

test('worker and controller use pinned upstream images and explicit local versions', () => {
  for (const source of [workerDockerfile, controllerDockerfile]) {
    assert.match(source, /FROM node:22\.17\.0-bookworm-slim@sha256:[a-f0-9]{64}/);
    assert.doesNotMatch(source, /:latest\b/);
  }
  assert.match(workerDockerfile, /FROM oven\/bun:1\.3\.14@sha256:[a-f0-9]{64}/);
  assert.match(workerDockerfile, /^USER 10001:10001$/m);
  assert.match(controllerDockerfile, /^USER 65532:65532$/m);
  assert.match(compose, /image:\s*siragpt-runsc-controller:0\.1\.0/);
  assert.match(compose, /RUNSC_SANDBOX_WORKER_IMAGE:\s*"\$\{RUNSC_SANDBOX_WORKER_IMAGE:-\}"/);
  assert.match(utils, /inspect\.Image !== config\.image/);
  assert.match(activityStore, /sira\.runsc-sandbox-activity\.v1/);
});

test('real gVisor workflow is path-gated, pinned, and exercises adversarial isolation', () => {
  assert.match(workflow, /runs-on:\s*ubuntu-24\.04/);
  assert.match(workflow, /RUNSC_VERSION:\s*release-\d{8}\.\d+/);
  assert.match(workflow, /RUNSC_SHA512_X86_64:\s*[a-f0-9]{128}/);
  assert.match(workflow, /actions\/checkout@[a-f0-9]{40}/);
  assert.doesNotMatch(workflow, /uses:\s*[^\s]+@(main|master|v\d+)\b/);
  assert.doesNotMatch(workflow, /:latest\b/);
  assert.match(workflow, /--mount type=bind,src=\/var\/run\/docker\.sock,dst=\/var\/run\/docker\.sock,readonly/);
  assert.match(workflow, /WORKER_IMAGE_ID=\$\{worker_image_id\}/);
  assert.match(workflow, /RUNSC_SANDBOX_WORKER_IMAGE="\$\{WORKER_IMAGE_ID\}"/);
  assert.match(workflow, /runtimeArgs == \["--platform=systrap", "--network=sandbox"\]/);
  assert.match(workflow, /--publish 127\.0\.0\.1:4098:4098/);
  assert.match(workflow, /test -z "\$\(docker ps -aq --filter label=com\.siragpt\.runsc-sandbox\.managed=true\)"/);
  for (const sourcePath of [
    'scripts/runsc-sandbox-*.js',
    'scripts/runsc-sandbox-*.mjs',
    'scripts/runsc-sandbox-*.Dockerfile',
    'backend/src/services/codex/sandbox-providers/**',
    'docker-compose.prod.yml',
  ]) {
    const occurrences = workflow.match(new RegExp(sourcePath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) || [];
    assert.equal(occurrences.length, 2, `${sourcePath} must gate pull_request and production-main push`);
  }
  assert.match(smoke, /sandbox B read A's workspace/);
  assert.match(smoke, /CONTROL_PLANE_BLOCKED/);
  assert.match(smoke, /NO_DEFAULT_ROUTE/);
  assert.match(smoke, /PID_LIMIT_ENFORCED/);
  assert.match(smoke, /exec_timeout/);
  assert.match(smoke, /memory pressure escaped the cgroup limit/);
  assert.match(smoke, /DELETE.*v1\/sandboxes/);
});

test('runsc controller and client suites are in the canonical sharded CI list', () => {
  const canonical = `${pkg.scripts.test} ${pkg.scripts['test:runsc-sandbox']}`;
  for (const file of [
    'tests/runsc-sandbox-controller.test.js',
    'tests/codex-runsc-sandbox-client.test.js',
    'tests/codex-runsc-production-contract.test.js',
  ]) {
    assert.ok(canonical.includes(file), `${file} is missing from canonical CI`);
  }
});
