'use strict';

const { test, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const PptxGenJS = require('pptxgenjs');

const artifactDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sgpt-pptx-delivery-quality-'));
process.env.AGENT_ARTIFACT_DIR = artifactDir;
const { validateDocument, buildPlan, buildPptxHtmlPreview, INTERNAL: pipelineInternal } = require('../src/services/document-pipeline/advanced-document-pipeline');
const { INTERNAL } = require('../src/services/agents/task-tools');
const sandbox = require('../src/services/agents/code-sandbox');
const objectStorage = require('../src/services/object-storage');
const { reviewArtifact } = require('../src/services/agents/artifact-reviewer');

after(() => fs.rmSync(artifactDir, { recursive: true, force: true }));

const defects = [
  { name: 'text outside the canvas', code: 'PPTX_TEXT_OUTSIDE_SLIDE', options: { x: 18, y: 15 } },
  { name: 'unreadable two-point text', code: 'PPTX_TEXT_TOO_SMALL', options: { fontSize: 2 } },
  { name: 'white text on an explicit white background', code: 'PPTX_TEXT_INVISIBLE_CONTRAST', options: { color: 'FFFFFF' } },
];

// These are actual editable Office packages generated by PptxGenJS. Enough
// substantive content is retained to pass the unrelated structural/content
// checks: the regression is layout safety, not a corrupt ZIP or empty slide.
async function makeDeck(defect = null) {
  const deck = new PptxGenJS();
  deck.layout = 'LAYOUT_WIDE';
  deck.author = 'SiraGPT QA';
  deck.subject = 'Prueba de entrega de presentaciones editables';
  deck.title = 'Plan de continuidad operativa';
  const contents = [
    ['Prioridades operativas', 'La continuidad operativa requiere responsables definidos, inventario de recursos críticos y seguimiento semanal de compromisos. El equipo revisa las dependencias entre áreas antes de aprobar el calendario de ejecución.'],
    ['Ejecución coordinada', 'Cada responsable confirma los recursos disponibles y registra los acuerdos de su área. Las reuniones semanales permiten identificar obstáculos, asignar acciones correctivas y mantener una secuencia de trabajo verificable.'],
    ['Seguimiento de resultados', 'La revisión mensual contrasta los compromisos con la evidencia registrada por cada equipo. Las desviaciones se documentan con una acción concreta, un responsable identificado y una fecha de seguimiento.'],
  ];
  for (const [index, [title, body]] of contents.entries()) {
    const slide = deck.addSlide();
    slide.background = { color: 'FFFFFF' };
    slide.addText(title, { x: 0.7, y: 0.6, w: 11.6, h: 0.8, fontFace: 'Arial', fontSize: 32, color: '172233', margin: 0, isTextBox: true });
    slide.addText(body, { x: 0.7, y: 2, w: 10.8, h: 2.3, fontFace: 'Arial', fontSize: 20, color: '334455', margin: 0, isTextBox: true, ...(index === 0 ? defect?.options : {}) });
  }
  return Buffer.from(await deck.write({ outputType: 'nodebuffer' }));
}

const contract = {
  required_extension: 'pptx',
  success_tests: [{ id: 'format', type: 'deterministic', check: 'extension_match', parameters: { value: 'pptx' }, description: 'Entrega un archivo PowerPoint editable' }],
};

function assertDesignRejection(result, defect) {
  assert.equal(result.passed, false, 'known design defects cannot be averaged into a passing score');
  assert.equal(result.checks.designSafety, false);
  assert.equal(result.checks.contentSpecific, true, 'the fixture contains sufficient substantive content');
  assert.equal(result.checks.uniqueTitles, true);
  assert.equal(result.details.designAudit.passed, false);
  assert.equal(result.details.designAudit.coverage.rendered, false, 'static preflight must not claim a visual render');
  assert.ok(result.details.designAudit.issues.some((issue) => issue.code === defect.code && issue.slide === 1 && issue.severity === 'error'));
}

for (const defect of defects) {
  test(`PPTX delivery validator rejects ${defect.name}`, async () => {
    const buffer = await makeDeck(defect);
    assertDesignRejection(validateDocument({ format: 'pptx', buffer }), defect);
  });
}

test('PPTX delivery validator accepts readable editable content', async () => {
  const result = validateDocument({ format: 'pptx', buffer: await makeDeck() });
  assert.equal(result.passed, true);
  assert.equal(result.checks.designSafety, true);
  assert.deepEqual(result.details.designAudit.issues, []);
  assert.equal(result.details.designAudit.coverage.slides, 3);
});

// The sandbox transport alone is mocked: no model, Python runtime or live
// endpoint is exercised here. Production validation, contract review and
// registration all receive the same real PPTX bytes, written to the exact
// OUT_PATH passed by create_document. This is not an authenticated E2E test.
function writeDeckThroughSandbox(t, getBuffer) {
  const writtenPaths = [];
  t.mock.method(objectStorage, 'enabled', () => false);
  t.mock.method(sandbox, 'run', async ({ language, source }) => {
    assert.equal(language, 'python');
    const assignment = source.match(/^os\.environ\["OUT_PATH"\] = (.+)$/m);
    assert.ok(assignment, 'create_document supplies an explicit output path');
    const target = JSON.parse(assignment[1]);
    assert.equal(path.dirname(target), artifactDir);
    fs.writeFileSync(target, getBuffer());
    writtenPaths.push(target);
    return { ok: true, stdout: '', stderr: '', timedOut: false };
  });
  return writtenPaths;
}

for (const defect of defects) {
  for (const withContract of [false, true]) {
    test(`create_document blocks ${defect.name} ${withContract ? 'even with a passing format contract' : 'without a contract'}`, async (t) => {
      const buffer = await makeDeck(defect);
      if (withContract) {
        assert.equal(reviewArtifact({ contract, artifact: { filename: 'continuidad.pptx', buffer } }).passed, true, 'the format-only contract must not mask design failure');
      }
      const writtenPaths = writeDeckThroughSandbox(t, () => buffer);
      const events = [];
      const result = await INTERNAL.createDocument.execute({ filename: 'continuidad.pptx', python: '# Transport fixture writes the generated PowerPoint bytes.' }, {
        userId: 'pptx-quality-test', chatId: 'pptx-quality-chat',
        ...(withContract ? { taskContract: contract } : {}),
        onEvent: (event) => events.push(event),
      });
      assert.equal(result.ok, false);
      assertDesignRejection(result.validation, defect);
      assert.equal(typeof result.repairHint, 'string');
      assert.ok(result.repairHint.trim().length > 20, 'the agent receives actionable repair feedback');
      assert.equal(result.artifactId, undefined);
      assert.equal(events.some((event) => event.type === 'file_artifact'), false);
      assert.ok(events.some((event) => event.type === 'tool_output' && event.tool === 'create_document' && event.ok === false));
      assert.equal(writtenPaths.length, 1);
      assert.equal(fs.existsSync(writtenPaths[0]), false, 'unsafe pending file is removed');
      assert.deepEqual(fs.readdirSync(artifactDir), [], 'neither an artifact nor metadata is registered');
    });
  }
}

test('create_document accepts a corrected PPTX and stores the design validation evidence', async (t) => {
  let buffer = await makeDeck(defects[0]);
  writeDeckThroughSandbox(t, () => buffer);
  const events = [];
  const ctx = { userId: 'pptx-repair-test', chatId: 'pptx-repair-chat', taskContract: contract, onEvent: (event) => events.push(event) };
  const args = { filename: 'continuidad-corregida.pptx', python: '# Transport fixture writes the generated PowerPoint bytes.' };
  const rejected = await INTERNAL.createDocument.execute(args, ctx);
  assert.equal(rejected.ok, false);
  assert.equal(events.some((event) => event.type === 'file_artifact'), false);
  buffer = await makeDeck();
  const accepted = await INTERNAL.createDocument.execute(args, ctx);
  assert.equal(accepted.ok, true);
  assert.equal(accepted.validation.passed, true);
  assert.equal(accepted.validation.checks.designSafety, true);
  const deliveries = events.filter((event) => event.type === 'file_artifact');
  assert.equal(deliveries.length, 1, 'only the corrected artifact becomes downloadable');
  assert.equal(deliveries[0].artifact.id, accepted.artifactId);
  const metadata = JSON.parse(fs.readFileSync(INTERNAL.metadataPathFor(accepted.artifactId), 'utf8'));
  assert.equal(metadata.validation.checks.designSafety, true);
  assert.equal(metadata.validation.details.designAudit.coverage.rendered, false);
  assert.deepEqual(metadata.validation.details.designAudit.issues, []);
});


function contentPreviewPlan() {
  const plan = buildPlan({ prompt: 'Crea una presentación de 8 diapositivas sobre continuidad operativa.', format: 'pptx', template: 'business' });
  plan.presentationTheme = 'minimal';
  plan.slidePlan = {
    topic: 'Continuidad operativa', thesis: 'Definir responsables y revisar los resultados.',
    references: Array.from({ length: 6 }, (_, index) => ({ name: `Fuente documental ${index + 1}`, excerpt: `Registro de seguimiento ${index + 1}.` })),
    slides: [
      { layout: 'bullets', title: 'Acciones de continuidad', bullets: [{ text: 'Identificar recursos.' }, { text: 'Asignar responsables.' }, { text: 'Acordar compromisos.' }, { text: 'Registrar resultados.' }, { text: 'Verificar recuperaciones semanales.' }] },
      { layout: 'two_column', title: 'Organización del seguimiento', columns: [{ heading: 'Preparación', items: ['Revisar recursos.', 'Acordar fechas.', 'Asignar tareas.', 'Verificar datos.', 'Confirmar la recuperación final.'] }, { heading: 'Ejecución', items: ['Registrar los acuerdos.'] }] },
      { layout: 'stat', title: 'Alcance de revisión', stat: { value: '24', caption: 'Participantes del ejercicio', source: 'Datos sintéticos.' }, support: ['Revisar participación.', 'Confirmar asistencia.', 'Conservar registros.', 'Documentar todas las observaciones.'] },
      { layout: 'quote', title: 'Criterio compartido', kicker: 'Guía de seguimiento', quote: 'Cada decisión debe contar con evidencia.', attribution: 'Equipo del ejercicio' },
      { layout: 'chart', title: 'Cierre de actividades registradas', chart: { type: 'column', title: 'Avance del ejercicio', labels: ['Inicio', 'Cierre'], values: [4, 8], yAxisTitle: 'Actividades', unit: 'registros', asOf: 'octubre', source: 'Datos sintéticos.' }, takeaway: 'Contrastar los avances con el registro.' },
    ],
  };
  return plan;
}

test('content preview retains all native PPTX bullets, column items, support, sources and chart takeaway', async () => {
  const outputDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sgpt-pptx-content-preview-'));
  try {
    const plan = contentPreviewPlan();
    const { buffer, filename } = await pipelineInternal.buildDocumentFile({ plan, outputDir });
    const zip = new (require('pizzip'))(buffer);
    const slideXml = Object.keys(zip.files).filter((name) => /^ppt\/slides\/slide\d+\.xml$/.test(name)).map((name) => zip.file(name).asText()).join('\n');
    const preview = buildPptxHtmlPreview(plan, filename);
    for (const value of ['Verificar recuperaciones semanales.', 'Confirmar la recuperación final.', 'Documentar todas las observaciones.', 'Fuente documental 6', 'Registro de seguimiento 6.', 'Criterio compartido', 'Guía de seguimiento', 'Contrastar los avances con el registro.']) {
      assert.ok(slideXml.includes(value), `native PPTX contains ${value}`);
      assert.ok(preview.includes(value), `content preview also contains ${value}`);
    }
    assert.ok(preview.includes('Avance del ejercicio'));
    assert.equal((preview.match(/aspect-ratio:16\/9/g) || []).length, 8);
    assert.match(preview, /Vista de contenido\. El diseño final se encuentra en el archivo PowerPoint\./);
    assert.doesNotMatch(preview, /replica el guion|overflow:hidden|position:absolute/);
    assert.equal((preview.match(/role="region" aria-label="Contenido de la diapositiva" tabindex="0"/g) || []).length, 8, 'long cards remain keyboard accessible');
  } finally {
    fs.rmSync(outputDir, { recursive: true, force: true });
  }
});

test('content preview retains long source excerpts and escapes user-provided text', () => {
  const plan = contentPreviewPlan();
  const excerpt = 'Antecedente documental comprobado. '.repeat(10) + 'FINAL DE LA FUENTE <script>texto</script>';
  plan.slidePlan.references[0].excerpt = excerpt;
  const preview = buildPptxHtmlPreview(plan, 'continuidad.pptx');
  assert.ok(preview.includes('FINAL DE LA FUENTE &lt;script&gt;texto&lt;/script&gt;'));
  assert.doesNotMatch(preview, /<script>/);
  assert.ok(preview.includes('Registro de seguimiento 6.'));
});

test('content preview includes every agenda item and stat fallback that exists in the deck', () => {
  const plan = contentPreviewPlan();
  plan.slideTarget = 12;
  plan.slidePlan.references = [];
  plan.slidePlan.slides[2].support = [];
  plan.slidePlan.slides[2].summary = 'Resumen de participación verificable.';
  plan.slidePlan.slides[2].takeaway = 'Conservar las observaciones del equipo.';
  for (let index = 6; index <= 10; index++) {
    plan.slidePlan.slides.push({ layout: 'bullets', title: index === 10 ? 'Cierre operativo número 10' : `Revisión operativa número ${index}`, bullets: [{ text: `Registrar el acuerdo ${index}.` }] });
  }
  const preview = buildPptxHtmlPreview(plan, 'continuidad.pptx');
  assert.equal((preview.match(/Cierre operativo número 10/g) || []).length, 2, 'last title is visible in both agenda and content');
  assert.ok(preview.includes('Resumen de participación verificable.'));
  assert.ok(preview.includes('Conservar las observaciones del equipo.'));
  assert.equal((preview.match(/aspect-ratio:16\/9/g) || []).length, 12);
});
