'use strict';

const assert = require('node:assert/strict');
const test = require('node:test');

const { classifyTaskError } = require('../src/utils/task-error-classifier');

const CASES = [
  // retryable rate/concurrency pressure
  ['rate limit exceeded', true, 'rate-limited'],
  ['RATE_LIMIT: requests per minute exceeded', true, 'rate-limited'],
  ['Too Many Requests', true, 'rate-limited'],
  ['resource exhausted by upstream model', true, 'rate-limited'],
  ['RPM limit exceeded', true, 'rate-limited'],
  ['TPM limit exceeded', true, 'rate-limited'],
  ['concurrency limit reached', true, 'rate-limited'],
  ['request was throttled', true, 'rate-limited'],
  ['slow down and retry later', true, 'rate-limited'],
  ['burst limit exceeded', true, 'rate-limited'],
  ['server busy, retry after 2 seconds', true, 'rate-limited'],
  [{ message: 'quota burst limit', statusCode: 429 }, true, 'rate-limited'],

  // retryable DNS/network/timeout failures
  ['ENOTFOUND api.provider.test', true, 'dns-failure'],
  ['EAI_AGAIN temporary name resolution failure', true, 'dns-failure'],
  ['getaddrinfo failed for provider', true, 'dns-failure'],
  ['DNS_PROBE_FINISHED_NXDOMAIN', true, 'dns-failure'],
  ['request timeout while streaming', true, 'network-timeout'],
  ['operation timed out', true, 'network-timeout'],
  ['ETIMEDOUT connect', true, 'network-timeout'],
  ['ECONNRESET while reading body', true, 'network-timeout'],
  ['ECONNREFUSED 127.0.0.1', true, 'network-timeout'],
  ['ECONNABORTED socket hang up', true, 'network-timeout'],
  ['EPIPE writing request body', true, 'network-timeout'],
  ['socket hang up', true, 'network-timeout'],
  ['gateway timeout from proxy', true, 'network-timeout'],
  [{ message: 'client timed out', statusCode: 408 }, true, 'network-timeout'],
  [{ message: 'upstream timeout', statusCode: 504 }, true, 'network-timeout'],

  // retryable SSL/TLS and server faults
  ['CERT_HAS_EXPIRED', true, 'ssl-error'],
  ['unable to verify the first certificate', true, 'ssl-error'],
  ['self signed certificate in certificate chain', true, 'ssl-error'],
  ['self-signed certificate', true, 'ssl-error'],
  ['DEPTH_ZERO_SELF_SIGNED_CERT', true, 'ssl-error'],
  ['SSL handshake failed', true, 'ssl-error'],
  ['TLS handshake timeout', true, 'network-timeout'],
  ['handshake failure', true, 'ssl-error'],
  ['internal server error', true, 'server-error'],
  ['service unavailable', true, 'server-error'],
  ['bad gateway from model provider', true, 'server-error'],
  ['upstream 503 overloaded', true, 'server-error'],
  ['502 bad gateway', true, 'server-error'],
  [{ message: 'provider exploded', statusCode: 500 }, true, 'server-error'],
  [{ message: 'maintenance', statusCode: 503 }, true, 'server-error'],

  // non-retryable cancellation/abort
  ['aborted by caller', false, 'aborted'],
  ['AbortError: request was aborted', false, 'aborted'],
  ['abort_err', false, 'aborted'],
  ['cancelled by user', false, 'aborted'],
  ['canceled by user', false, 'aborted'],
  ['ERR_CANCELED', false, 'aborted'],
  ['operation was canceled', false, 'aborted'],
  ['context canceled', false, 'aborted'],
  ['context deadline exceeded', false, 'aborted'],
  ['client closed request', false, 'aborted'],
  ['user interrupted run', false, 'aborted'],
  ['shutdown in progress', false, 'aborted'],

  // non-retryable prompt/context/policy/auth
  ['context_length_exceeded', false, 'context-length'],
  ['context length exceeded', false, 'context-length'],
  ['context window is full', false, 'context-length'],
  ['maximum context length exceeded', false, 'context-length'],
  ['prompt is too long', false, 'context-length'],
  ['too many tokens in prompt', false, 'context-length'],
  ['token limit exceeded', false, 'context-length'],
  ['input token limit reached', false, 'context-length'],
  ['output token limit exceeded', false, 'context-length'],
  ['token budget exceeded', false, 'context-length'],
  ['maximum prompt length exceeded', false, 'context-length'],
  ['please reduce the length', false, 'context-length'],
  ['content_policy violation', false, 'content-policy'],
  ['content policy blocked the response', false, 'content-policy'],
  ['policy_violation', false, 'content-policy'],
  ['safety filter blocked content', false, 'content-policy'],
  ['safety system rejected request', false, 'content-policy'],
  ['flagged by moderation', false, 'content-policy'],
  ['terms of service policy block', false, 'content-policy'],
  ['responsible ai policy refusal', false, 'content-policy'],
  ['unsafe content detected', false, 'content-policy'],
  ['guardrail intervention', false, 'content-policy'],
  ['jailbreak detected', false, 'content-policy'],
  ['disallowed content', false, 'content-policy'],
  ['api_key missing', false, 'auth-failure'],
  ['api key invalid', false, 'auth-failure'],
  ['authentication failed', false, 'auth-failure'],
  ['permission denied', false, 'auth-failure'],
  ['forbidden request', false, 'auth-failure'],
  ['unauthorized_client', false, 'auth-failure'],
  ['invalid bearer token', false, 'auth-failure'],
  ['expired token', false, 'auth-failure'],
  ['missing authorization header', false, 'auth-failure'],
  ['does not have access to model', false, 'auth-failure'],
  ['not entitled for endpoint', false, 'auth-failure'],
  [{ message: 'no auth', statusCode: 401 }, false, 'auth-failure'],
  [{ message: 'blocked', statusCode: 403 }, false, 'auth-failure'],

  // non-retryable validation/config/model/payload/billing
  ['missing required field taskId', false, 'validation-error'],
  ['required field userId missing', false, 'validation-error'],
  ['invalid json body', false, 'validation-error'],
  ['schema validation failed', false, 'validation-error'],
  ['malformed request body', false, 'validation-error'],
  ['unsupported file type', false, 'validation-error'],
  ['invalid enum value', false, 'validation-error'],
  ['request body must be an object', false, 'validation-error'],
  ['zod validation error', false, 'validation-error'],
  ['provider not configured', false, 'validation-error'],
  ['invalid webhook signature', false, 'validation-error'],
  ['model_not_found', false, 'model-unavailable'],
  ['model not found', false, 'model-unavailable'],
  ['deployment not found', false, 'model-unavailable'],
  ['deprecated model requested', false, 'model-unavailable'],
  ['model has been retired', false, 'model-unavailable'],
  ['engine not found', false, 'model-unavailable'],
  ['model is not enabled', false, 'model-unavailable'],
  ['unknown model alias', false, 'model-unavailable'],
  ['model temporarily disabled', false, 'model-unavailable'],
  ['payload too large', false, 'payload-too-large'],
  ['request entity too large', false, 'payload-too-large'],
  ['content too large', false, 'payload-too-large'],
  ['body exceeded max size', false, 'payload-too-large'],
  ['max upload size exceeded', false, 'payload-too-large'],
  ['file size exceeds limit', false, 'payload-too-large'],
  ['response too large', false, 'payload-too-large'],
  ['artifact exceeds max bytes', false, 'payload-too-large'],
  ['image is too large', false, 'payload-too-large'],
  ['multipart body exceeded', false, 'payload-too-large'],
  ['insufficient_quota', false, 'quota-exhausted'],
  ['insufficient quota', false, 'quota-exhausted'],
  ['quota exceeded', false, 'quota-exhausted'],
  ['billing hard limit reached', false, 'quota-exhausted'],
  ['payment required', false, 'quota-exhausted'],
  ['monthly usage limit reached', false, 'quota-exhausted'],
  ['credits exhausted', false, 'quota-exhausted'],
  ['no available credits', false, 'quota-exhausted'],
  ['subscription inactive', false, 'quota-exhausted'],
  ['free tier limit reached', false, 'quota-exhausted'],
  ['spend cap exceeded', false, 'quota-exhausted'],
  [{ message: 'pay up', statusCode: 402 }, false, 'quota-exhausted'],
  ['not implemented', false, 'not-implemented'],
  [{ message: 'missing method', statusCode: 501 }, false, 'not-implemented'],
];

test('classifyTaskError covers at least 100 production error fingerprints', () => {
  assert.ok(CASES.length >= 100, `expected at least 100 cases, got ${CASES.length}`);
  for (const [input, retryable, reason] of CASES) {
    const result = classifyTaskError(input instanceof Error || typeof input === 'object' ? input : new Error(input));
    assert.equal(result.retryable, retryable, `${input} retryable`);
    assert.equal(result.reason, reason, `${input} reason`);
    if (retryable) assert.ok(result.ttlMs > 0, `${input} should include retry TTL`);
  }
});
