// AUTO-GENERATED by scripts/generate-prisma-types-for-frontend.js.
// DO NOT EDIT BY HAND. Re-run the generator to regenerate.
// Source: backend/prisma/schema.prisma
//
// Scope (cycle 42 scaffold): 5 models, sensitive fields stripped,
// relations dropped. Extend ALLOWED_MODELS in the generator to add more.

export interface User {
  id: string;
  email: string;
  name: string;
  avatar?: string;
  plan: string;
  isAdmin: boolean;
  isSuperAdmin: boolean;
  apiUsage: bigint;
  monthlyCallLimit: bigint;
  monthlyLimit: bigint;
  gmailTokens?: string;
  googleServicesTokens?: string;
  spotifyTokens?: string;
  subscriptionStatus?: string;
  subscriptionEndDate?: string;
  locale?: string;
  preferredTone?: string;
  customInstructions?: string;
  settings?: unknown;
  lastActiveAt?: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string;
  searchBrainSettings?: string;
}

export interface Chat {
  id: string;
  userId: string;
  title: string;
  model: string;
  createdAt: string;
  updatedAt: string;
  isShared: boolean;
  shareId?: string;
  isArchived: boolean;
  deletedAt?: string;
  preferredResponseLanguage?: string;
  googleCalendarContext?: unknown;
  isWordConnectorChat: boolean;
  wordContent?: string;
  isExcelConnectorChat: boolean;
  excelContent?: unknown;
  customGptId?: string;
  projectId?: string;
  organizationId?: string;
  sharedAt?: string;
}

export interface Message {
  id: string;
  chatId: string;
  role: string;
  content: string;
  tokens?: bigint;
  timestamp: string;
  files?: unknown;
  metadata?: unknown;
  feedback?: string;
  deletedAt?: string;
  content_tsv?: string;
}

export interface AgentTask {
  id: string;
  userId: string;
  chatId?: string;
  jobId?: string;
  status: string;
  goal: string;
  model?: string;
  traceId?: string;
  documentPolicy?: unknown;
  state?: unknown;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
  cancelledAt?: string;
  failedAt?: string;
}

export interface File {
  id: string;
  userId: string;
  filename: string;
  originalName: string;
  mimeType: string;
  size: number;
  path: string;
  extractedText?: string;
  openaiFileId?: string;
  createdAt: string;
  processingStage?: string;
  processingError?: string;
  processingStageAt?: string;
  documentAnalysis?: string;
  customGptId?: string;
  projectId?: string;
  deletedAt?: string;
}
