"use client"

import * as React from "react"
import { useState, useRef, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { ScrollArea } from "@/components/ui/scroll-area"
import {
  Eye,
  EyeOff,
  Copy,
  Check,
  Download,
  Maximize2,
  Minimize2,
  RefreshCw,
  ExternalLink,
  FileCode,
  Package,
  PanelRight,
  X
} from "lucide-react"
import { toast } from "sonner"

interface CodePreviewProps {
  htmlCode?: string
  cssCode?: string
  jsCode?: string
  combinedCode?: string
  title?: string
  language?: string
  className?: string
  onClose?: () => void
}

export const CodePreview: React.FC<CodePreviewProps> = ({
  htmlCode = "",
  cssCode = "",
  jsCode = "",
  combinedCode = "",
  title = "Code Preview",
  language = "html",
  className = "",
  onClose
}) => {
  const [isPreviewVisible, setIsPreviewVisible] = useState(true)
  const [isFullscreen, setIsFullscreen] = useState(false)

  const [isCopied, setIsCopied] = useState(false)
  const [previewKey, setPreviewKey] = useState(0)
  const iframeRef = useRef<HTMLIFrameElement>(null)

  // Generate combined HTML document with enhanced quality
  const generateCompleteHTML = () => {
    if (combinedCode) {
      return combinedCode
    }

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes, minimum-scale=1.0, maximum-scale=5.0">
    <title>${title}</title>
    <meta name="description" content="Generated by AI Assistant - Modern responsive web application">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        /* Enhanced CSS Reset & Modern Base Styles */
        *, *::before, *::after {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        
        html {
            font-size: 16px;
            scroll-behavior: smooth;
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
        }
        
        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #1a202c;
            background-color: #ffffff;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            font-feature-settings: 'kern' 1;
        }
        
        /* Modern responsive utilities */
        .container { max-width: 1200px; margin: 0 auto; padding: 0 1rem; }
        .flex { display: flex; }
        .grid { display: grid; }
        .hidden { display: none; }
        .block { display: block; }
        .w-full { width: 100%; }
        .h-full { height: 100%; }
        .min-h-screen { min-height: 100vh; }
        .text-center { text-align: center; }
        .rounded { border-radius: 0.375rem; }
        .shadow { box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06); }
        .transition { transition: all 0.3s ease; }
        
        /* Responsive breakpoints */
        @media (max-width: 768px) {
            .container { padding: 0 0.75rem; }
            html { font-size: 14px; }
        }
        
        @media (max-width: 480px) {
            .container { padding: 0 0.5rem; }
        }
        
        /* Enhanced button styles */
        button, .btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            padding: 0.75rem 1.5rem;
            border: none;
            border-radius: 0.375rem;
            font-weight: 500;
            text-decoration: none;
            cursor: pointer;
            transition: all 0.2s ease;
            font-family: inherit;
        }
        
        button:hover, .btn:hover {
            transform: translateY(-1px);
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
        }
        
        /* Form improvements */
        input, textarea, select {
            font-family: inherit;
            font-size: inherit;
            padding: 0.75rem;
            border: 1px solid #d1d5db;
            border-radius: 0.375rem;
            transition: border-color 0.2s ease;
        }
        
        input:focus, textarea:focus, select:focus {
            outline: none;
            border-color: #3b82f6;
            box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
        }
        
        /* Custom styles */
        ${cssCode}
    </style>
</head>
<body>
    <div id="app">
        ${htmlCode}
    </div>
    
    <script>
        // Enhanced error handling and utilities
        window.onerror = function(msg, url, line, col, error) {
            console.error('Preview Error:', msg, 'at line', line);
            return false;
        };
        
        window.addEventListener('unhandledrejection', function(event) {
            console.error('Unhandled promise rejection:', event.reason);
        });
        
        // Utility functions
        const $ = (selector) => document.querySelector(selector);
        const $$ = (selector) => document.querySelectorAll(selector);
        
        // DOM ready handler
        document.addEventListener('DOMContentLoaded', function() {
            console.log('App initialized successfully');
            
            // Add smooth scrolling for anchor links
            $$('a[href^="#"]').forEach(anchor => {
                anchor.addEventListener('click', function (e) {
                    e.preventDefault();
                    const target = $(this.getAttribute('href'));
                    if (target) {
                        target.scrollIntoView({ behavior: 'smooth' });
                    }
                });
            });
            
            // Custom JavaScript
            ${jsCode}
        });
        
        // Performance monitoring
        window.addEventListener('load', function() {
            console.log('Page fully loaded in', performance.now(), 'ms');
        });
    </script>
</body>
</html>`
  }

  // Update iframe content
  useEffect(() => {
    if (iframeRef.current && (htmlCode || cssCode || jsCode || combinedCode)) {
      const completeHTML = generateCompleteHTML()
      const blob = new Blob([completeHTML], { type: 'text/html' })
      const url = URL.createObjectURL(blob)
      iframeRef.current.src = url

      return () => {
        URL.revokeObjectURL(url)
      }
    }
  }, [htmlCode, cssCode, jsCode, combinedCode, previewKey])

  // Copy complete code to clipboard
  const handleCopy = async () => {
    try {
      const completeCode = generateCompleteHTML()
      await navigator.clipboard.writeText(completeCode)
      setIsCopied(true)
      toast.success("Code copied to clipboard!")
      setTimeout(() => setIsCopied(false), 2000)
    } catch (error) {
      toast.error("Failed to copy code")
    }
  }

  // Download as HTML file
  const handleDownload = () => {
    const completeCode = generateCompleteHTML()
    const blob = new Blob([completeCode], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${title.toLowerCase().replace(/\s+/g, '-')}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success("File downloaded!")
  }

  // Generate optimized single-file project with modern features
  const handleGenerateProject = () => {
    const modernReset = `
    /* Modern CSS Reset */
    *, *::before, *::after { box-sizing: border-box; }
    * { margin: 0; padding: 0; }
    html, body { height: 100%; }
    body { line-height: 1.6; -webkit-font-smoothing: antialiased; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    img, picture, video, canvas, svg { display: block; max-width: 100%; }
    input, button, textarea, select { font: inherit; }
    p, h1, h2, h3, h4, h5, h6 { overflow-wrap: break-word; }
    `

    const utilities = `
    /* Utility Classes */
    .container { max-width: 1200px; margin: 0 auto; padding: 0 1rem; }
    .text-center { text-align: center; }
    .flex { display: flex; }
    .items-center { align-items: center; }
    .justify-center { justify-content: center; }
    .w-full { width: 100%; }
    .rounded { border-radius: 0.375rem; }
    .shadow { box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); }
    @media (max-width: 768px) { .container { padding: 0 0.5rem; } }
    `

    const optimizedCode = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Generated by AI Assistant">
    <title>${title}</title>
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🌐</text></svg>">
    <style>
        ${modernReset}
        ${utilities}
        ${cssCode}
        
        html { scroll-behavior: smooth; }
        .loading { opacity: 0; animation: fadeIn 0.5s ease-in-out forwards; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
    </style>
</head>
<body>
    <div id="app" class="loading">
        ${htmlCode}
    </div>
    
    <script>
        window.onerror = function(msg, url, line, col, error) {
            console.error('Error:', msg, 'at line', line);
            return false;
        };
        
        document.addEventListener('DOMContentLoaded', function() {
            console.log('Page loaded successfully!');
            document.getElementById('app').classList.add('loading');
            
            ${jsCode}
        });
        
        function $(selector) { return document.querySelector(selector); }
        function $$(selector) { return document.querySelectorAll(selector); }
        function scrollTo(selector) {
            const element = $(selector);
            if (element) element.scrollIntoView({ behavior: 'smooth' });
        }
    </script>
</body>
</html>`

    const blob = new Blob([optimizedCode], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${title.toLowerCase().replace(/\s+/g, '-')}-optimized.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success("Optimized project downloaded with modern features!")
  }

  // Refresh preview
  const handleRefresh = () => {
    setPreviewKey(prev => prev + 1)
  }

  // Toggle fullscreen
  const toggleFullscreen = () => {
    setIsFullscreen(!isFullscreen)
  }

  if (!htmlCode && !cssCode && !jsCode && !combinedCode) {
    return null
  }

  return (
    <div className={`${className} ${isFullscreen ? 'fixed inset-0 z-50 bg-background' : 'h-full'}`}>
      <Card className={`${isFullscreen ? 'h-full flex flex-col' : 'h-full flex flex-col'} border border-border shadow-sm bg-card`}>
        <CardHeader className="pb-3 bg-muted/50 border-b border-border">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileCode className="h-4 w-4 text-primary" />
              <CardTitle className="text-sm font-medium text-card-foreground">{title}</CardTitle>
            </div>
            <div className="flex items-center gap-1">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setIsPreviewVisible(!isPreviewVisible)}
                className="h-8 w-8 p-0"
              >
                {isPreviewVisible ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleRefresh}
                className="h-8 w-8 p-0"
              >
                <RefreshCw className="h-4 w-4" />
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCopy}
                className="h-8 w-8 p-0"
              >
                {isCopied ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleDownload}
                className="h-8 w-8 p-0"
                title="Download basic HTML file"
              >
                <Download className="h-4 w-4" />
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleGenerateProject}
                className="h-8 w-8 p-0"
                title="Download optimized single-file project"
              >
                <Package className="h-4 w-4" />
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={toggleFullscreen}
                className="h-8 w-8 p-0"
              >
                {isFullscreen ? <Minimize2 className="h-4 w-4" /> : <Maximize2 className="h-4 w-4" />}
              </Button>
              {onClose && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={onClose}
                  className="h-8 w-8 p-0"
                  title="Close preview"
                >
                  <X className="h-4 w-4" />
                </Button>
              )}
            </div>
          </div>
        </CardHeader>

        {isPreviewVisible && (
          <CardContent className="p-0 flex-grow">
            <div className="h-full border-t border-border">
              <iframe
                ref={iframeRef}
                key={previewKey}
                className="w-full h-full border-0 bg-white dark:bg-gray-900 rounded-b-lg"
                sandbox="allow-scripts allow-same-origin allow-forms allow-modals allow-popups"
                title={title}
                loading="lazy"
              />
            </div>
          </CardContent>
        )}
      </Card>
    </div>
  )
}

export default CodePreview
