/**
 * Curated Apps catalog shown at the foot of /gpts.
 * Connection state lives in settings.apps[id].connected.
 */

export type GptStoreAppCategory =
  | "Empleo"
  | "Inmuebles"
  | "Autos"
  | "Compras"
  | "Astrología"
  | "Comida"
  | "Noticias"
  | "Otros"

export type GptStoreApp = {
  id: string
  name: string
  description: string
  category: GptStoreAppCategory
}

export const GPT_STORE_APP_CATEGORIES: { value: "All" | GptStoreAppCategory; label: string }[] = [
  { value: "All", label: "Todas" },
  { value: "Empleo", label: "Empleo" },
  { value: "Inmuebles", label: "Inmuebles" },
  { value: "Autos", label: "Autos" },
  { value: "Compras", label: "Compras" },
  { value: "Astrología", label: "Astrología" },
  { value: "Comida", label: "Comida" },
  { value: "Noticias", label: "Noticias" },
  { value: "Otros", label: "Otros" },
]

export const GPT_STORE_APPS: GptStoreApp[] = [
  { id: "indeed", name: "Indeed", description: "Find jobs tailored for you", category: "Empleo" },
  { id: "linkedin", name: "LinkedIn", description: "Find the right professional", category: "Empleo" },
  { id: "tarot", name: "Tarot", description: "Tarot Reading & Divination", category: "Astrología" },
  { id: "idealista", name: "idealista", description: "Find properties to buy or rent", category: "Inmuebles" },
  { id: "ask-tarot-cards", name: "Ask Tarot Cards", description: "Tarot card readings", category: "Astrología" },
  { id: "etsy", name: "Etsy", description: "Shop Home, Style & More", category: "Compras" },
  { id: "steer-astro", name: "Steer Astro", description: "Your Personal AI Astrologer", category: "Astrología" },
  { id: "homey", name: "Homey", description: "A better smart home.", category: "Otros" },
  { id: "astro-scope-astrology", name: "Astro Scope: Astrology", description: "Birth Chart, Horoscope Ai", category: "Astrología" },
  { id: "astro-scope-tarot", name: "Astro Scope: Tarot", description: "Daily 3-card tarot reading", category: "Astrología" },
  { id: "12andus-astrology", name: "12andus Astrology", description: "Charts, future & compatibility", category: "Astrología" },
  { id: "astrologic", name: "Astrologic", description: "Birth charts and horoscopes", category: "Astrología" },
  { id: "appy-coupons", name: "Appy Coupons", description: "Find coupons with ChatGPT", category: "Compras" },
  { id: "all-your-horoscopes", name: "All your Horoscopes", description: "Zodiac, star signs, astrology!", category: "Astrología" },
  { id: "true-sky", name: "True Sky", description: "Astrology readings & horoscope", category: "Astrología" },
  { id: "autoscout24", name: "AutoScout24", description: "Automobile buying and leasing", category: "Autos" },
  { id: "minty", name: "Minty", description: "Get Paid to Shop", category: "Compras" },
  { id: "redfin", name: "Redfin", description: "Find and tour homes for sale", category: "Inmuebles" },
  { id: "autotrader", name: "Autotrader", description: "Search for new and used cars", category: "Autos" },
  { id: "jobicy", name: "Jobicy", description: "Search remote jobs", category: "Empleo" },
  { id: "haaretz", name: "Haaretz", description: "Query Haaretz with ChatGPT", category: "Noticias" },
  { id: "realestate-com-au", name: "realestate.com.au", description: "Search Australian property", category: "Inmuebles" },
  { id: "a-z-holy-bible", name: "A-Z Holy Bible", description: "Study Scripture+Chapter+Verse", category: "Otros" },
  { id: "zen-shopping", name: "Zen Shopping", description: "Smart shopping, all stores", category: "Compras" },
  { id: "triastra-astrology-saju", name: "TriAstra Astrology & Saju", description: "Birth Chart & Vedic Horoscope", category: "Astrología" },
  { id: "pandafind", name: "PandaFind", description: "Search AliExpress better", category: "Otros" },
  { id: "tomorrow-io-weather", name: "Tomorrow.io Weather", description: "Explore weather by location", category: "Otros" },
  { id: "newsify", name: "Newsify", description: "Trending news, any country", category: "Noticias" },
  { id: "astro-scope-destiny-matrix", name: "Astro Scope Destiny Matrix", description: "Destiny Matrix by birth date", category: "Astrología" },
  { id: "lume", name: "Lume", description: "Find your place in Campinas", category: "Otros" },
  { id: "square-yards", name: "Square Yards", description: "Find properties in India", category: "Inmuebles" },
  { id: "loft", name: "Loft", description: "Find your next property", category: "Inmuebles" },
  { id: "powerly", name: "Powerly", description: "EV charging insights", category: "Otros" },
  { id: "octopart-component-finder", name: "Octopart Component Finder", description: "Find parts and prices", category: "Otros" },
  { id: "all-tide-times", name: "All Tide Times", description: "Tide heights, times and more", category: "Otros" },
  { id: "figaro-immobilier", name: "Figaro Immobilier", description: "Find the ideal property", category: "Inmuebles" },
  { id: "auto", name: "Auto", description: "Connect Camera Roll & Photos", category: "Otros" },
  { id: "anyvan", name: "AnyVan", description: "Move anything anywhere", category: "Otros" },
  { id: "coches-net", name: "coches.net", description: "Find new and used cars", category: "Autos" },
  { id: "eesel-shopping-assistant", name: "eesel Shopping Assistant", description: "Find products and reviews", category: "Compras" },
  { id: "ridelogger", name: "RideLogger", description: "Track vehicle maintenance", category: "Autos" },
  { id: "ordering-tools", name: "Ordering.Tools", description: "Ordering for Restaurants", category: "Comida" },
  { id: "innovist", name: "Innovist", description: "Clean Transparent Science", category: "Inmuebles" },
  { id: "blibli", name: "Blibli", description: "Find original products & deals", category: "Compras" },
  { id: "belk", name: "Belk", description: "Fashion, Shoes, Beauty & More", category: "Compras" },
  { id: "ai-booker", name: "AI Booker", description: "Book your table.", category: "Otros" },
  { id: "rentals-ca-rental-search", name: "Rentals.ca Rental Search", description: "Rental search in Canada", category: "Inmuebles" },
  { id: "arabica-uae", name: "% Arabica UAE", description: "Order % Arabica coffee UAE", category: "Comida" },
  { id: "tillys", name: "Tillys", description: "Shop clothing, Shoes & Accesso", category: "Compras" },
  { id: "freediver", name: "Freediver", description: "Plan freediving workouts", category: "Otros" },
  { id: "cowboy-model-finder", name: "Cowboy Model Finder", description: "Find your perfect Cowboy ebike", category: "Autos" },
  { id: "here-comes-the-guide", name: "Here Comes The Guide", description: "Find your dream wedding venue", category: "Otros" },
  { id: "chotot", name: "Chotot", description: "Find cars, electronics, goods", category: "Autos" },
  { id: "braai-bbq-planner", name: "Braai BBQ Planner", description: "Plan BBQ cooks", category: "Comida" },
  { id: "pararius", name: "Pararius", description: "Find your new home", category: "Otros" },
  { id: "gmarket", name: "Gmarket", description: "Find products and deals", category: "Compras" },
  { id: "mercado-libre-inmuebles", name: "Mercado Libre Inmuebles", description: "Find your ideal property", category: "Inmuebles" },
  { id: "develoop", name: "Develoop", description: "Ship GitHub work end to end", category: "Otros" },
  { id: "simple-world-clock", name: "Simple World Clock", description: "Check the time, any time", category: "Otros" },
  { id: "kleinanzeigen", name: "Kleinanzeigen", description: "Echte Deals. Echte Menschen.", category: "Compras" },
  { id: "quoted", name: "Quoted", description: "See any quote", category: "Otros" },
  { id: "avito-ma", name: "Avito.ma", description: "Classifieds in Morocco", category: "Otros" },
  { id: "yapay-zeka-n-n-boyner-i", name: "Yapay Zeka'nın Boyner'i", description: "Online Alışverişin Adresi", category: "Otros" },
  { id: "onsellr-marketplace", name: "Onsellr Marketplace", description: "Find cars in Australia", category: "Autos" },
  { id: "printa", name: "PrintA", description: "Print your image on a shirt", category: "Otros" },
  { id: "photographer-finder-by-hb", name: "Photographer Finder by HB", description: "Find & book HoneyBook pros", category: "Otros" },
  { id: "guyal", name: "Guyal", description: "Find everyday jewelry", category: "Otros" },
  { id: "elko", name: "ELKO", description: "Raftækjaverslun á Íslandi", category: "Otros" },
  { id: "tastewise", name: "Tastewise", description: "Insights for Food & Beverage", category: "Comida" },
  { id: "softonic", name: "Softonic", description: "Search and discover software", category: "Otros" },
  { id: "cafe24", name: "Cafe24", description: "Search, explore, and shop", category: "Compras" },
  { id: "swiggy-food", name: "Swiggy Food", description: "Order food from your favorites", category: "Comida" },
  { id: "iq-sell-my-car", name: "IQ Sell My Car", description: "Value and sell your car", category: "Autos" },
  { id: "cargo", name: "Cargo", description: "GTM engineering for agents", category: "Otros" },
  { id: "soul-family-ai", name: "Soul Family AI", description: "Meditations and teachings", category: "Otros" },
  { id: "hausmann-immobilien", name: "Hausmann Immobilien", description: "Properties in Hamburg", category: "Inmuebles" },
  { id: "nailie-beauty", name: "Nailie Beauty", description: "Search Nailie beautists", category: "Compras" },
  { id: "historial-de-vehiculos-espana", name: "Historial de Vehiculos España", description: "Datos coche por matrícula", category: "Otros" },
  { id: "weavify", name: "Weavify", description: "Bangkok dining & nightlife", category: "Otros" },
  { id: "mumzworld", name: "Mumzworld", description: "Shop for baby and kids", category: "Compras" },
  { id: "private-md-labs", name: "Private MD Labs", description: "Understand your biology fast", category: "Otros" },
  { id: "freshblooms", name: "FreshBlooms", description: "Send beautiful, fresh flowers.", category: "Otros" },
  { id: "techsource-marketplace", name: "TechSource Marketplace", description: "Shop tech & find products", category: "Compras" },
  { id: "access-yami", name: "Access Yami", description: "Shop all of Asia's best", category: "Compras" },
  { id: "unni", name: "Unni", description: "Explore medical procedure", category: "Otros" },
  { id: "homesni-property-search", name: "HomesNI Property Search", description: "Find HomesNI property listings", category: "Inmuebles" },
  { id: "systembolaget", name: "Systembolaget", description: "Find products and stores", category: "Compras" },
  { id: "channel3-shopping", name: "Channel3 Shopping", description: "Shop products across the web", category: "Compras" },
  { id: "donedeal", name: "DoneDeal", description: "Find the most new & used cars", category: "Autos" },
  { id: "luxauto", name: "Luxauto", description: "Cars and moto to buy and lease", category: "Autos" },
  { id: "montreat-heating-and-cooling", name: "Montreat Heating and Cooling", description: "HVAC pricing and booking.", category: "Otros" },
  { id: "tiendanube", name: "TiendaNube", description: "Gestiona tu tienda en línea", category: "Otros" },
  { id: "shipal", name: "Shipal", description: "Track any package by tracking", category: "Otros" },
  { id: "skylit-studio-custom-gifts", name: "Skylit Studio Custom Gifts", description: "Make a moment unforgettable", category: "Otros" },
  { id: "le-parisien", name: "Le Parisien", description: "Toute l'actualité en un clic", category: "Noticias" },
  { id: "hookradar", name: "HookRadar", description: "SMM and Ads creative research", category: "Otros" },
  { id: "simplysefer", name: "SimplySefer", description: "Search seforim listings", category: "Inmuebles" },
  { id: "remodeleriq", name: "RemodelerIQ", description: "Is your contractor bid fair?", category: "Otros" },
  { id: "ac-artificial-conscience", name: "AC - Artificial Conscience®", description: "The Christian Moral Layer", category: "Otros" },
  { id: "app", name: "요기요", description: "배달할 때마다 포인트 적립", category: "Otros" },
  { id: "nejo", name: "Nejo", description: "Stellenangebote durchsuchen", category: "Empleo" },
  { id: "imoveis-magiko-ia", name: "Imóveis Magiko IA", description: "Encontre imóveis com IA", category: "Inmuebles" },
  { id: "lifestyle-helper", name: "Lifestyle Helper", description: "Trusted tips for daily life", category: "Otros" },
  { id: "boostermage", name: "Boostermage", description: "Compare UK MTG prices", category: "Otros" },
  { id: "connectlinx", name: "Connectlinx", description: "Run your real estate business", category: "Inmuebles" },
  { id: "lalso-rsvp-invites", name: "Lalso RSVP — Invites", description: "Online invites, RSVPs & guests", category: "Otros" },
  { id: "pricey-monitor-history-alerts", name: "Pricey- monitor+history+alerts", description: "Track+watch shopping products", category: "Compras" },
  { id: "red-estelar", name: "Red Estelar", description: "Homes for sale or rent", category: "Inmuebles" },
  { id: "carsleuth", name: "CarSleuth", description: "Investigate used cars", category: "Autos" },
  { id: "a-z-dog-breeds", name: "A-Z Dog Breeds", description: "Every breed, all the details", category: "Otros" },
  { id: "municibid", name: "Municibid", description: "Find government auctions", category: "Otros" },
  { id: "confused-com", name: "Confused.com", description: "Check your vehicle tax", category: "Autos" },
  { id: "3byggetilbud-dk", name: "3byggetilbud.dk", description: "Find håndværkere hurtigt", category: "Otros" },
  { id: "getir", name: "Getir", description: "delivery in minutes", category: "Otros" },
  { id: "champfy", name: "Champfy", description: "Find Tennis|Pickleball partner", category: "Otros" },
  { id: "carslink-ai", name: "CarsLink.ai", description: "Search UK cars, vans & bikes", category: "Autos" },
  { id: "batoo-used-boats", name: "Batoo - Used Boats", description: "Find and compare used boats", category: "Autos" },
  { id: "perchli-property-search", name: "Perchli Property Search", description: "Search NI Properties", category: "Inmuebles" },
  { id: "closai", name: "Closai", description: "Personal Inventory Management", category: "Otros" },
  { id: "meetup", name: "Meetup", description: "Find local social events", category: "Otros" },
  { id: "paardplaats-horse-finder", name: "Paardplaats Horse Finder", description: "Find horses for sale worldwide", category: "Otros" },
  { id: "justlife", name: "Justlife", description: "Find and book home services", category: "Otros" },
  { id: "landwirt-com", name: "Landwirt.com", description: "Find agricultural machinery", category: "Otros" },
  { id: "safe2sign-contract-risk-check", name: "Safe2Sign: Contract Risk Check", description: "Review Agreement for Red Flags", category: "Otros" },
  { id: "spaartje", name: "Spaartje", description: "Compare grocery prices", category: "Comida" },
  { id: "webuycars", name: "WeBuyCars", description: "Search cars and sell yours", category: "Autos" },
  { id: "polypo", name: "Polypo", description: "Find your size. See your fit.", category: "Otros" },
  { id: "immobilien-immoprofessional", name: "Immobilien immoprofessional", description: "Find real estate across EU", category: "Inmuebles" },
  { id: "anvaya", name: "Anvaya", description: "Plan your multi-event Wedding", category: "Otros" },
  { id: "standvirtual", name: "Standvirtual", description: "Your dream car in Standvirtual", category: "Autos" },
  { id: "dolphin-fitness", name: "Dolphin Fitness", description: "Shop fitness & wellbeing", category: "Compras" },
  { id: "denison-yachting", name: "Denison Yachting", description: "Search yachts for sale", category: "Autos" },
  { id: "din-bostad", name: "Din Bostad", description: "Find Swedish property listings", category: "Inmuebles" },
  { id: "fragella-discover-your-scent", name: "Fragella: Discover Your Scent", description: "Discover Your Signature Scent", category: "Otros" },
  { id: "patriot-conceptions", name: "Patriot Conceptions", description: "Preview profiles", category: "Otros" },
  { id: "elfai-fashion-stylist", name: "elfai: Fashion Stylist", description: "Find personalized outfits", category: "Compras" },
  { id: "klinger-vogt-immobilien", name: "Klinger-Vogt Immobilien", description: "Rhine-Neckar Real Estate", category: "Inmuebles" },
  { id: "trocafone", name: "Trocafone", description: "Find pre-owned smartphones", category: "Otros" },
  { id: "samrum", name: "SAMRUM", description: "Family personality profiles", category: "Otros" },
  { id: "liftosaur", name: "Liftosaur", description: "Create scriptable workouts", category: "Otros" },
  { id: "journaling-with-medome", name: "Journaling with Medome", description: "Build Your Daily Journal", category: "Otros" },
  { id: "horizon-shield", name: "HORIZON SHIELD", description: "Check Japan reform estimates", category: "Otros" },
  { id: "tessie", name: "Tessie", description: "Access and control your Tesla", category: "Autos" },
  { id: "cliqueimudei", name: "CliqueiMudei", description: "Find properties and homes", category: "Inmuebles" },
  { id: "rolf-automobile-showroom", name: "Rolf Automobile Showroom", description: "Find cars from our inventory", category: "Autos" },
  { id: "imovirtual", name: "Imovirtual", description: "Find real estate in Portugal", category: "Inmuebles" },
  { id: "athome", name: "atHome", description: "Find properties to buy or rent", category: "Inmuebles" },
  { id: "eydost-esim", name: "Eydost Esim", description: "Instant eSIM in 150+ countries", category: "Otros" },
  { id: "alldiscgolf", name: "AllDiscGolf", description: "Compare disc golf prices", category: "Otros" },
  { id: "immo-der-vr-bank-rhein-neckar", name: "Immo der VR Bank Rhein-Neckar", description: "Properties in the Rhine-Neckar", category: "Inmuebles" },
  { id: "doctorsim-mobile-topups", name: "doctorSIM Mobile Topups", description: "Mobile Top-ups and Recharges", category: "Otros" },
  { id: "immobiliare-it", name: "Immobiliare.it", description: "The N.1 for selling and buying", category: "Inmuebles" },
  { id: "the-lonely-door", name: "The Lonely Door", description: "Enter through The Lonely Door", category: "Otros" },
  { id: "app-2", name: "무신사", description: "Find by style, pick by reviews", category: "Otros" },
  { id: "nash-agent", name: "Nash Agent", description: "AI-powered shopping agent", category: "Compras" },
  { id: "mycolive", name: "MYCOlive", description: "Home Rental Platform", category: "Inmuebles" },
  { id: "amore-mall", name: "아모레몰 AMORE MALL", description: "공식 브랜드 쇼핑부터 스마트 뷰티 케어까지", category: "Compras" },
  { id: "internshala", name: "Internshala", description: "Find internships & jobs", category: "Empleo" },
  { id: "metz-immobilien", name: "Metz Immobilien", description: "Frankfurt Properties", category: "Inmuebles" },
  { id: "vaktim", name: "Vaktim", description: "Quran and prayer times", category: "Otros" },
  { id: "the-wildfire-tracker", name: "The Wildfire tracker", description: "Fire map", category: "Otros" },
  { id: "break-the-web-news", name: "Break The Web News", description: "Get the latest news and trends", category: "Noticias" },
  { id: "vw-sign-drive", name: "VW Sign & Drive", description: "Find VW car subscription plans", category: "Autos" },
  { id: "mondoir-art", name: "Mondoir.art", description: "Find artworks for your space", category: "Otros" },
  { id: "smartcustomer", name: "SmartCustomer", description: "Business ratings and reviews", category: "Otros" },
  { id: "scangym", name: "ScanGym", description: "Find and book gym day passes", category: "Otros" },
  { id: "automotion", name: "AutoMotion", description: "Car Maintenance & Repair", category: "Autos" },
  { id: "promocodes-com", name: "Promocodes.com", description: "Find verified promo codes", category: "Compras" },
  { id: "penny", name: "Penny", description: "Shop deals, track prices", category: "Compras" },
  { id: "dispatcher-city", name: "Dispatcher.City", description: "Search Berlin property", category: "Inmuebles" },
  { id: "saltybytes", name: "SaltyBytes", description: "Find and save real recipes", category: "Comida" },
  { id: "spee24-shopping", name: "Spee24 Shopping", description: "Find and buy products easily", category: "Compras" },
  { id: "trovaprezzi-it", name: "Trovaprezzi.it", description: "Confronta prezzi prodotti", category: "Otros" },
  { id: "mrv", name: "MRV", description: "Conecta você ao apê ideal", category: "Compras" },
  { id: "botala-by-dyskute", name: "Botala by dyskute", description: "Commandez partout", category: "Otros" },
  { id: "artue", name: "artue", description: "Find art with natural language", category: "Otros" },
  { id: "digimarket", name: "Digimarket", description: "Find industrial stock", category: "Compras" },
  { id: "cora", name: "Cora", description: "Personal health coach", category: "Otros" },
  { id: "pantry-persona", name: "Pantry Persona", description: "Meal Plans, Recipes, Inventory", category: "Comida" },
  { id: "milanuncios", name: "Milanuncios", description: "Search second hand items", category: "Otros" },
  { id: "fotocasa", name: "Fotocasa", description: "Find properties to buy or rent", category: "Inmuebles" },
  { id: "mimove", name: "MiMove", description: "Sale in Spain and Portugal", category: "Otros" },
  { id: "tuespaciopr", name: "TuEspacioPR", description: "Search Puerto Rico Listings", category: "Inmuebles" },
  { id: "home-connect", name: "Home Connect", description: "Bosch, Siemens, Gaggenau, NEFF", category: "Otros" },
  { id: "rifo-home", name: "RIFO Home", description: "Find Homes to Buy and Rent", category: "Inmuebles" },
  { id: "olx-india", name: "OLX India", description: "Search OLX listings", category: "Inmuebles" },
  { id: "deglaze", name: "Deglaze", description: "Chat with your recipe library", category: "Comida" },
  { id: "airtasker", name: "Airtasker", description: "Post tasks and hire taskers", category: "Otros" },
  { id: "karaca", name: "Karaca", description: "Karaca Ürünlerini Keşfet!", category: "Otros" },
  { id: "nuvemshop", name: "Nuvemshop", description: "Gerencie sua loja online", category: "Compras" },
  { id: "housetospot-immobilien", name: "HouseToSpot Immobilien", description: "Find the right property faster", category: "Inmuebles" },
  { id: "bandsintown", name: "Bandsintown", description: "Find concerts and tour dates", category: "Otros" },
  { id: "catholic-index", name: "Catholic Index", description: "Find Mass times and churches", category: "Otros" },
  { id: "skillmap-pro", name: "Skillmap Pro", description: "Servicios y trabajo en Chile", category: "Empleo" },
  { id: "nameeasy", name: "NameEasy", description: "Find Indian Baby Names", category: "Otros" },
  { id: "japanbox-kz", name: "JapanBox.kz", description: "Shop Japan via chat", category: "Compras" },
  { id: "dewa", name: "DEWA", description: "View bills, services and more.", category: "Otros" },
  { id: "keuzehulp-studio", name: "Keuzehulp Studio", description: "Hulp bij keuzes", category: "Otros" },
  { id: "lfmall", name: "LFmall", description: "나를 나답게 만드는 취향 발견, LFmall AI 쇼핑", category: "Compras" },
  { id: "onyx-coach", name: "Onyx Coach", description: "Coach clients and workouts", category: "Otros" },
  { id: "otomoto", name: "OTOMOTO", description: "Znajdź auto marzeń w OTOMOTO", category: "Autos" },
  { id: "carwale", name: "CarWale", description: "Find, research & compare cars", category: "Autos" },
  { id: "background-changer", name: "Background Changer", description: "Discover website themes", category: "Otros" },
  { id: "simply-wedding", name: "Simply-Wedding", description: "Heiraten leicht gemacht", category: "Otros" },
  { id: "kingpin-market", name: "Kingpin Market", description: "Fingerboard marketplace", category: "Compras" },
  { id: "hepapal", name: "HepaPal", description: "Track drinking gently", category: "Otros" },
  { id: "casepoint", name: "Casepoint", description: "eDiscovery, Legal Hold & FOIA", category: "Otros" },
  { id: "webaz-shopping", name: "WebAZ Shopping", description: "Find reviewed physical goods", category: "Compras" },
  { id: "korea-concierge", name: "Korea Concierge", description: "Korea help with proof", category: "Otros" },
  { id: "luma", name: "Luma", description: "Find and manage events", category: "Otros" },
  { id: "tessun-immobilien", name: "Tessun Immobilien", description: "Properties Munich & ILT", category: "Inmuebles" },
  { id: "klinger-immobilien", name: "KLINGER Immobilien", description: "Berlin Area Properties", category: "Inmuebles" },
  { id: "nicebabyname-nameology", name: "NiceBabyName — Nameology", description: "Read baby names by nameology", category: "Otros" },
  { id: "immobilien-franzen", name: "Immobilien Franzen", description: "Eifel and Trier Properties", category: "Inmuebles" },
  { id: "clickdealer", name: "ClickDealer", description: "Search used cars in the UK", category: "Autos" },
  { id: "peristyle-grocery-cart", name: "Peristyle Grocery Cart", description: "Recipes into a grocery cart", category: "Comida" },
  { id: "who-what-wear", name: "Who What Wear", description: "Editor picks, tuned to you", category: "Otros" },
  { id: "magneto-empleos", name: "Magneto Empleos", description: "Search Jobs with AI", category: "Empleo" },
  { id: "cashback-hive-deals-coupons", name: "Cashback Hive: Deals & Coupons", description: "Save on every purchase", category: "Compras" },
  { id: "1-2-3-cook-bake-food-to-eat", name: "1-2-3-Cook+Bake Food to eat!", description: "Find recipes+baking+meals+prep", category: "Comida" },
  { id: "app-3", name: "전자랜드", description: "전문가가 고르고, 혜택은 더하고", category: "Otros" },
  { id: "pearl-auto", name: "Pearl Auto", description: "Verify car answers", category: "Autos" },
  { id: "robin", name: "robin", description: "Finds your next dream home", category: "Otros" },
  { id: "hepsiemlak", name: "hepsiemlak", description: "Find Your Home with Ease", category: "Otros" },
  { id: "clutch", name: "Clutch", description: "Buy & sell used cars in Canada", category: "Autos" },
  { id: "midi-libre", name: "Midi Libre", description: "L’info locale en continu", category: "Noticias" },
  { id: "spoonpal", name: "SpoonPal", description: "Analyze meals and get recipes", category: "Comida" },
  { id: "annstracts", name: "Annstracts", description: "Discover abstract photography", category: "Otros" },
  { id: "boulanger-achat-en-ligne", name: "Boulanger - Achat en ligne", description: "Electroménager & Multimedia", category: "Otros" },
  { id: "dominio-tech-delivery", name: "Dominio Tech Delivery", description: "Peça comida pelo ChatGPT", category: "Otros" },
  { id: "love-and-lemons", name: "Love and Lemons", description: "Find recipes and plan meals", category: "Comida" },
  { id: "lucid-beads", name: "Lucid Beads", description: "Create your dream bracelet", category: "Otros" },
  { id: "app-4", name: "올리브영", description: "Discover beauty, Find yours", category: "Compras" },
  { id: "dillr", name: "Dillr", description: "Save recipes, plan meals, cook", category: "Comida" },
  { id: "nipp", name: "$nipp", description: "Find Deals. Earn Rewards.", category: "Compras" },
  { id: "cars24", name: "CARS24", description: "Find your dream car", category: "Autos" },
  { id: "cellfusion-c", name: "CellFusion C", description: "Skincare picks", category: "Otros" },
  { id: "apexlog", name: "ApexLog", description: "Query your track day logbook", category: "Otros" },
  { id: "muju", name: "Muju", description: "Discover and order locally", category: "Otros" },
  { id: "onx-offroad", name: "onX Offroad", description: "Find offroad trails", category: "Otros" },
  { id: "product-link-expander", name: "Product Link Expander", description: "Expand product links", category: "Compras" },
  { id: "foodora", name: "foodora", description: "Find restaurants and menus", category: "Comida" },
  { id: "progressive-clarity", name: "Progressive Clarity", description: "Orient, explore naturally", category: "Otros" },
  { id: "anybarcodescanner", name: "AnyBarcodeScanner", description: "Scan and discuss products", category: "Compras" },
  { id: "cj", name: "CJ온스타일", description: "Live shopping, your style", category: "Compras" },
  { id: "stars-in-hands-gift-studio", name: "Stars In Hands Gift Studio", description: "Personalized gift proofs", category: "Otros" },
  { id: "pacelab-intervals", name: "Pacelab Intervals", description: "Create interval workouts", category: "Otros" },
  { id: "inoreader", name: "Inoreader", description: "Build your own newsfeed", category: "Noticias" },
  { id: "rilev", name: "Rilev", description: "Personalize your chats", category: "Otros" },
  { id: "outfit-lens", name: "Outfit Lens", description: "Snap a look, shop it instantly", category: "Compras" },
  { id: "anyreg", name: "AnyReg", description: "Get number plate vehicle info!", category: "Autos" },
  { id: "fryd", name: "Fryd", description: "Your Gardening Companion", category: "Otros" },
  { id: "quintoandar", name: "QuintoAndar", description: "Find your ideal home", category: "Inmuebles" },
  { id: "emlakjet", name: "Emlakjet", description: "Search and filter real estate", category: "Inmuebles" },
  { id: "wallector", name: "Wallector", description: "Discover and buy fine art", category: "Compras" },
  { id: "bayut-ksa", name: "Bayut KSA", description: "Find homes in the KSA", category: "Inmuebles" },
  { id: "drums-kit-learn-improve-w-ai", name: "Drums kit- Learn+improve w AI!", description: "Coach+Practice play,beat,fills", category: "Otros" },
  { id: "rotv-guide", name: "RoTV Guide", description: "Live Romanian TV guide", category: "Otros" },
  { id: "refermate", name: "Refermate", description: "Find deals and rewards", category: "Compras" },
  { id: "spotahome", name: "Spotahome", description: "Find rental homes", category: "Inmuebles" },
  { id: "crbonfree", name: "Crbonfree", description: "Estimate and offset CO2", category: "Otros" },
  { id: "remode", name: "Remode", description: "Shop any outfit from a photo", category: "Compras" },
  { id: "car-handshake", name: "Car Handshake", description: "Find cars for sale near you", category: "Autos" },
  { id: "myregistry-com", name: "MyRegistry.com", description: "All Stores, One Registry®", category: "Compras" },
  { id: "gs", name: "우리동네GS", description: "우리 일상 속 GS를 더 가깝게", category: "Otros" },
  { id: "maysynthel-shopping", name: "Maysynthel Shopping", description: "Maysynthel fashion & lifestyle", category: "Compras" },
  { id: "print-com", name: "Print.com", description: "Explore and price printing", category: "Otros" },
  { id: "wild-calf-coffee", name: "Wild Calf Coffee", description: "Find and brew better coffee", category: "Comida" },
  { id: "cand-reciclam", name: "Când Reciclăm", description: "Bucharest recycling schedules", category: "Otros" },
  { id: "chaiz", name: "Chaiz", description: "Compare car warranty quotes", category: "Autos" },
  { id: "grailpeople-shopping", name: "GrailPeople Shopping", description: "Find honest product reviews", category: "Compras" },
  { id: "sangria", name: "Sangria", description: "Buy products online", category: "Compras" },
  { id: "experteer", name: "Experteer", description: "Find Your Next Leadership Role", category: "Empleo" },
  { id: "gathrd", name: "Gathrd", description: "Shop, Save & Track Products", category: "Compras" },
  { id: "skw-immobilien", name: "SKW Immobilien", description: "Gütersloh properties", category: "Inmuebles" },
  { id: "tawadoo-buy-sell-auctions", name: "Tawadoo: Buy, Sell, Auctions", description: "Morocco classifieds, auctions", category: "Compras" },
  { id: "product-hunt", name: "Product Hunt", description: "The best new products in tech.", category: "Compras" },
  { id: "3-2-1-go-stopwatch", name: "3-2-1 Go Stopwatch", description: "Ready... set... go!", category: "Otros" },
  { id: "carparts-com", name: "Carparts.com", description: "Find best quality auto parts", category: "Autos" },
  { id: "pc-express", name: "PC Express", description: "Buy groceries online", category: "Comida" },
  { id: "zola", name: "Zola", description: "Find wedding vendors", category: "Otros" },
  { id: "imeb-eva-buchholz", name: "IMEB - Eva Buchholz", description: "Real estate expert for Munich", category: "Inmuebles" },
  { id: "la-centrale", name: "La Centrale", description: "Trouver votre véhicule", category: "Otros" },
  { id: "real-random", name: "Real Random", description: "Generate truly random values", category: "Otros" },
  { id: "diretora-criativa-sell-pro", name: "Diretora Criativa Sell Pro", description: "Imagens CRO para marketplaces", category: "Compras" },
  { id: "public-storage", name: "Public Storage", description: "Find self-storage space units", category: "Otros" },
  { id: "workopia", name: "Workopia", description: "Jobs, career advice & resumes", category: "Empleo" },
  { id: "buywise", name: "BuyWise", description: "Find best prices, real reviews", category: "Compras" },
  { id: "la-depeche-du-midi", name: "La Dépêche du Midi", description: "Toute l’actualité en continu", category: "Noticias" },
  { id: "wellness-coach", name: "Wellness Coach", description: "On-demand wellness guidance", category: "Otros" },
  { id: "lott-immobilien", name: "Lott Immobilien", description: "Leer to Oldenburg properties", category: "Inmuebles" },
  { id: "engel-volkers", name: "Engel & Völkers", description: "Find property listings", category: "Inmuebles" },
  { id: "app-5", name: "Реалистимо", description: "Realestate properties Bulgaria", category: "Inmuebles" },
  { id: "gethumandesign-com", name: "gethumandesign.com", description: "Explore your human design", category: "Otros" },
  { id: "laundryheap", name: "Laundryheap", description: "Book laundry pickups", category: "Otros" },
  { id: "tixel", name: "Tixel", description: "Find Tixel tickets", category: "Otros" },
  { id: "calories-club", name: "Calories Club", description: "Track meals and nutrition", category: "Comida" },
  { id: "endurance-planner", name: "Endurance Planner", description: "Plan your endurance", category: "Otros" },
  { id: "monnier-paris", name: "Monnier Paris", description: "Luxury catalog in ChatGPT", category: "Otros" },
  { id: "spacecloud-global", name: "SpaceCloud Global", description: "International rental spaces", category: "Empleo" },
  { id: "greystar-apartment-scout", name: "Greystar Apartment Scout", description: "Search over 1M apartments", category: "Inmuebles" },
  { id: "rakhys", name: "Rakhys", description: "Find best electronics prices", category: "Otros" },
  { id: "website-launches", name: "Website Launches", description: "Check launch dates & trust", category: "Otros" },
  { id: "chefjojo", name: "ChefJoJo", description: "Your magical kitchen sidekick", category: "Otros" },
  { id: "barfoot-thompson-homes", name: "Barfoot & Thompson Homes", description: "Search NZ property listings", category: "Inmuebles" },
  { id: "carsguide", name: "CarsGuide", description: "Find cars, prices and reviews.", category: "Autos" },
  { id: "angler-adventures-lure-guide", name: "Angler Adventures: Lure Guide", description: "Match lures to lake conditions", category: "Otros" },
  { id: "daft-ie", name: "Daft.ie", description: "Find Irish Properties for sale", category: "Inmuebles" },
  { id: "raptive-food", name: "Raptive Food", description: "Find recipes you can trust", category: "Comida" },
  { id: "0-100-wifi-internet-speed-test", name: "0-100 WiFi Internet Speed Test", description: "Broadband, Online Network, 5G", category: "Empleo" },
  { id: "bayut", name: "Bayut", description: "Find homes in the UAE", category: "Inmuebles" },
  { id: "foodpanda", name: "foodpanda", description: "Find restaurants and menus", category: "Comida" },
  { id: "trail-hits-bicycle-maintenance", name: "Trail Hits:Bicycle Maintenance", description: "Track your Bike's maintenance", category: "Otros" },
  { id: "rozetka", name: "Rozetka: інтернет гіпермаркет", description: "Search and order products", category: "Compras" },
  { id: "zinde-ai-free-calorie-tracker", name: "Zinde AI Free Calorie Tracker", description: "Track meals, water, exercise", category: "Comida" },
  { id: "eland-mall", name: "이랜드몰 ELAND MALL", description: "사는 즐거움이 있는 이랜드 공식 라이프스타일 몰", category: "Compras" },
  { id: "motos-net", name: "motos.net", description: "Find new and used motorbikes", category: "Autos" },
  { id: "kokiko", name: "Kokiko", description: "Find beauty products fast", category: "Compras" },
  { id: "autovit-ro", name: "Autovit.ro", description: "Find your dream car in Autovit", category: "Autos" },
  { id: "shopback", name: "ShopBack", description: "Get cashback for your shopping", category: "Compras" },
  { id: "wundercinemate", name: "WunderCineMate", description: "Discover and manage Movies!", category: "Otros" },
  { id: "letra-da-lei", name: "Letra da Lei", description: "Brazilian legal research", category: "Otros" },
  { id: "gumtree", name: "Gumtree", description: "Search Gumtree listings", category: "Inmuebles" },
]

