/**
 * Curated Apps catalog shown at the foot of /gpts.
 * Connection state for first-party OAuth apps is health-backed via /api/apps/connections.
 */

export type GptStoreAppCategory =
  | "Empleo"
  | "Inmuebles"
  | "Autos"
  | "Compras"
  | "Astrología"
  | "Comida"
  | "Noticias"
  | "Otros"

export type GptStoreApp = {
  id: string
  name: string
  description: string
  category: GptStoreAppCategory
  domain: string
}

export {
  gptStoreAppLogoSources,
  gptStoreAppLogoUrl,
} from "./gpts-app-logos"

export const GPT_STORE_APP_CATEGORIES: { value: "All" | GptStoreAppCategory; label: string }[] = [
  { value: "All", label: "Todas" },
  { value: "Empleo", label: "Empleo" },
  { value: "Inmuebles", label: "Inmuebles" },
  { value: "Autos", label: "Autos" },
  { value: "Compras", label: "Compras" },
  { value: "Astrología", label: "Astrología" },
  { value: "Comida", label: "Comida" },
  { value: "Noticias", label: "Noticias" },
  { value: "Otros", label: "Otros" },
]

export const GPT_STORE_APPS: GptStoreApp[] = [
  { id: "indeed", name: "Indeed", description: "Find jobs tailored for you", category: "Empleo", domain: "indeed.com" },
  { id: "linkedin", name: "LinkedIn", description: "Find the right professional", category: "Empleo", domain: "linkedin.com" },
  { id: "github", name: "GitHub", description: "Code, repos and collaboration", category: "Otros", domain: "github.com" },
  { id: "x", name: "X", description: "Posts and public conversation", category: "Noticias", domain: "x.com" },
  { id: "facebook", name: "Facebook", description: "Pages and social publishing", category: "Otros", domain: "facebook.com" },
  { id: "tarot", name: "Tarot", description: "Tarot Reading & Divination", category: "Astrología", domain: "labyrinthos.co" },
  { id: "idealista", name: "idealista", description: "Find properties to buy or rent", category: "Inmuebles", domain: "idealista.com" },
  { id: "ask-tarot-cards", name: "Ask Tarot Cards", description: "Tarot card readings", category: "Astrología", domain: "labyrinthos.co" },
  { id: "etsy", name: "Etsy", description: "Shop Home, Style & More", category: "Compras", domain: "etsy.com" },
  { id: "steer-astro", name: "Steer Astro", description: "Your Personal AI Astrologer", category: "Astrología", domain: "steerastro.com" },
  { id: "homey", name: "Homey", description: "A better smart home.", category: "Otros", domain: "homey.app" },
  { id: "astro-scope-astrology", name: "Astro Scope: Astrology", description: "Birth Chart, Horoscope Ai", category: "Astrología", domain: "astroscope.ai" },
  { id: "astro-scope-tarot", name: "Astro Scope: Tarot", description: "Daily 3-card tarot reading", category: "Astrología", domain: "astroscope.ai" },
  { id: "12andus-astrology", name: "12andus Astrology", description: "Charts, future & compatibility", category: "Astrología", domain: "12andus.com" },
  { id: "astrologic", name: "Astrologic", description: "Birth charts and horoscopes", category: "Astrología", domain: "astrologic.io" },
  { id: "appy-coupons", name: "Appy Coupons", description: "Find coupons with ChatGPT", category: "Compras", domain: "appycoupons.com" },
  { id: "all-your-horoscopes", name: "All your Horoscopes", description: "Zodiac, star signs, astrology!", category: "Astrología", domain: "horoscope.com" },
  { id: "true-sky", name: "True Sky", description: "Astrology readings & horoscope", category: "Astrología", domain: "truesky.app" },
  { id: "autoscout24", name: "AutoScout24", description: "Automobile buying and leasing", category: "Autos", domain: "autoscout24.com" },
  { id: "minty", name: "Minty", description: "Get Paid to Shop", category: "Compras", domain: "minty.com" },
  { id: "redfin", name: "Redfin", description: "Find and tour homes for sale", category: "Inmuebles", domain: "redfin.com" },
  { id: "autotrader", name: "Autotrader", description: "Search for new and used cars", category: "Autos", domain: "autotrader.com" },
  { id: "jobicy", name: "Jobicy", description: "Search remote jobs", category: "Empleo", domain: "jobicy.com" },
  { id: "haaretz", name: "Haaretz", description: "Query Haaretz with ChatGPT", category: "Noticias", domain: "haaretz.com" },
  { id: "realestate-com-au", name: "realestate.com.au", description: "Search Australian property", category: "Inmuebles", domain: "realestate.com.au" },
  { id: "a-z-holy-bible", name: "A-Z Holy Bible", description: "Study Scripture+Chapter+Verse", category: "Otros", domain: "a-z-holy-bible.com" },
  { id: "zen-shopping", name: "Zen Shopping", description: "Smart shopping, all stores", category: "Compras", domain: "zenshopping.com" },
  { id: "triastra-astrology-saju", name: "TriAstra Astrology & Saju", description: "Birth Chart & Vedic Horoscope", category: "Astrología", domain: "triastra-astrology-saju.com" },
  { id: "pandafind", name: "PandaFind", description: "Search AliExpress better", category: "Otros", domain: "aliexpress.com" },
  { id: "tomorrow-io-weather", name: "Tomorrow.io Weather", description: "Explore weather by location", category: "Otros", domain: "tomorrow.io" },
  { id: "newsify", name: "Newsify", description: "Trending news, any country", category: "Noticias", domain: "newsify.co" },
  { id: "astro-scope-destiny-matrix", name: "Astro Scope Destiny Matrix", description: "Destiny Matrix by birth date", category: "Astrología", domain: "astro-scope-destiny-matrix.com" },
  { id: "lume", name: "Lume", description: "Find your place in Campinas", category: "Otros", domain: "lume.com" },
  { id: "square-yards", name: "Square Yards", description: "Find properties in India", category: "Inmuebles", domain: "squareyards.com" },
  { id: "loft", name: "Loft", description: "Find your next property", category: "Inmuebles", domain: "loft.com.br" },
  { id: "powerly", name: "Powerly", description: "EV charging insights", category: "Otros", domain: "powerly.ai" },
  { id: "octopart-component-finder", name: "Octopart Component Finder", description: "Find parts and prices", category: "Otros", domain: "octopart.com" },
  { id: "all-tide-times", name: "All Tide Times", description: "Tide heights, times and more", category: "Otros", domain: "all-tide-times.com" },
  { id: "figaro-immobilier", name: "Figaro Immobilier", description: "Find the ideal property", category: "Inmuebles", domain: "immobilier.lefigaro.fr" },
  { id: "auto", name: "Auto", description: "Connect Camera Roll & Photos", category: "Otros", domain: "auto.com" },
  { id: "anyvan", name: "AnyVan", description: "Move anything anywhere", category: "Otros", domain: "anyvan.com" },
  { id: "coches-net", name: "coches.net", description: "Find new and used cars", category: "Autos", domain: "coches.net" },
  { id: "eesel-shopping-assistant", name: "eesel Shopping Assistant", description: "Find products and reviews", category: "Compras", domain: "eesel-shopping-assistant.com" },
  { id: "ridelogger", name: "RideLogger", description: "Track vehicle maintenance", category: "Autos", domain: "ridelogger.com" },
  { id: "ordering-tools", name: "Ordering.Tools", description: "Ordering for Restaurants", category: "Comida", domain: "ordering.tools" },
  { id: "innovist", name: "Innovist", description: "Clean Transparent Science", category: "Inmuebles", domain: "innovist.com" },
  { id: "blibli", name: "Blibli", description: "Find original products & deals", category: "Compras", domain: "blibli.com" },
  { id: "belk", name: "Belk", description: "Fashion, Shoes, Beauty & More", category: "Compras", domain: "belk.com" },
  { id: "ai-booker", name: "AI Booker", description: "Book your table.", category: "Otros", domain: "ai-booker.com" },
  { id: "rentals-ca-rental-search", name: "Rentals.ca Rental Search", description: "Rental search in Canada", category: "Inmuebles", domain: "rentals.ca" },
  { id: "arabica-uae", name: "% Arabica UAE", description: "Order % Arabica coffee UAE", category: "Comida", domain: "arabica.ae" },
  { id: "tillys", name: "Tillys", description: "Shop clothing, Shoes & Accesso", category: "Compras", domain: "tillys.com" },
  { id: "freediver", name: "Freediver", description: "Plan freediving workouts", category: "Otros", domain: "freediver.com" },
  { id: "cowboy-model-finder", name: "Cowboy Model Finder", description: "Find your perfect Cowboy ebike", category: "Autos", domain: "cowboy.com" },
  { id: "here-comes-the-guide", name: "Here Comes The Guide", description: "Find your dream wedding venue", category: "Otros", domain: "herecomestheguide.com" },
  { id: "chotot", name: "Chotot", description: "Find cars, electronics, goods", category: "Autos", domain: "chotot.com" },
  { id: "braai-bbq-planner", name: "Braai BBQ Planner", description: "Plan BBQ cooks", category: "Comida", domain: "braai-bbq-planner.com" },
  { id: "pararius", name: "Pararius", description: "Find your new home", category: "Otros", domain: "pararius.com" },
  { id: "gmarket", name: "Gmarket", description: "Find products and deals", category: "Compras", domain: "gmarket.co.kr" },
  { id: "mercado-libre-inmuebles", name: "Mercado Libre Inmuebles", description: "Find your ideal property", category: "Inmuebles", domain: "mercadolibre.com" },
  { id: "develoop", name: "Develoop", description: "Ship GitHub work end to end", category: "Otros", domain: "develoop.com" },
  { id: "simple-world-clock", name: "Simple World Clock", description: "Check the time, any time", category: "Otros", domain: "simple-world-clock.com" },
  { id: "kleinanzeigen", name: "Kleinanzeigen", description: "Echte Deals. Echte Menschen.", category: "Compras", domain: "kleinanzeigen.de" },
  { id: "quoted", name: "Quoted", description: "See any quote", category: "Otros", domain: "quoted.com" },
  { id: "avito-ma", name: "Avito.ma", description: "Classifieds in Morocco", category: "Otros", domain: "avito.ma" },
  { id: "yapay-zeka-n-n-boyner-i", name: "Yapay Zeka'nın Boyner'i", description: "Online Alışverişin Adresi", category: "Otros", domain: "boyner.com.tr" },
  { id: "onsellr-marketplace", name: "Onsellr Marketplace", description: "Find cars in Australia", category: "Autos", domain: "onsellr-marketplace.com" },
  { id: "printa", name: "PrintA", description: "Print your image on a shirt", category: "Otros", domain: "printa.com" },
  { id: "photographer-finder-by-hb", name: "Photographer Finder by HB", description: "Find & book HoneyBook pros", category: "Otros", domain: "photographer-finder-by-hb.com" },
  { id: "guyal", name: "Guyal", description: "Find everyday jewelry", category: "Otros", domain: "guyal.com" },
  { id: "elko", name: "ELKO", description: "Raftækjaverslun á Íslandi", category: "Otros", domain: "elko.is" },
  { id: "tastewise", name: "Tastewise", description: "Insights for Food & Beverage", category: "Comida", domain: "tastewise.io" },
  { id: "softonic", name: "Softonic", description: "Search and discover software", category: "Otros", domain: "softonic.com" },
  { id: "cafe24", name: "Cafe24", description: "Search, explore, and shop", category: "Compras", domain: "cafe24.com" },
  { id: "swiggy-food", name: "Swiggy Food", description: "Order food from your favorites", category: "Comida", domain: "swiggy.com" },
  { id: "iq-sell-my-car", name: "IQ Sell My Car", description: "Value and sell your car", category: "Autos", domain: "iqcars.net" },
  { id: "cargo", name: "Cargo", description: "GTM engineering for agents", category: "Otros", domain: "cargo.com" },
  { id: "soul-family-ai", name: "Soul Family AI", description: "Meditations and teachings", category: "Otros", domain: "soul-family-ai.com" },
  { id: "hausmann-immobilien", name: "Hausmann Immobilien", description: "Properties in Hamburg", category: "Inmuebles", domain: "hausmann-immobilien.com" },
  { id: "nailie-beauty", name: "Nailie Beauty", description: "Search Nailie beautists", category: "Compras", domain: "nailie.jp" },
  { id: "historial-de-vehiculos-espana", name: "Historial de Vehiculos España", description: "Datos coche por matrícula", category: "Otros", domain: "historial-de-vehiculos-espana.com" },
  { id: "weavify", name: "Weavify", description: "Bangkok dining & nightlife", category: "Otros", domain: "weavify.com" },
  { id: "mumzworld", name: "Mumzworld", description: "Shop for baby and kids", category: "Compras", domain: "mumzworld.com" },
  { id: "private-md-labs", name: "Private MD Labs", description: "Understand your biology fast", category: "Otros", domain: "privatemdlabs.com" },
  { id: "freshblooms", name: "FreshBlooms", description: "Send beautiful, fresh flowers.", category: "Otros", domain: "freshblooms.com" },
  { id: "techsource-marketplace", name: "TechSource Marketplace", description: "Shop tech & find products", category: "Compras", domain: "techsource-marketplace.com" },
  { id: "access-yami", name: "Access Yami", description: "Shop all of Asia's best", category: "Compras", domain: "access-yami.com" },
  { id: "unni", name: "Unni", description: "Explore medical procedure", category: "Otros", domain: "unni.com" },
  { id: "homesni-property-search", name: "HomesNI Property Search", description: "Find HomesNI property listings", category: "Inmuebles", domain: "homesni-property-search.com" },
  { id: "systembolaget", name: "Systembolaget", description: "Find products and stores", category: "Compras", domain: "systembolaget.se" },
  { id: "channel3-shopping", name: "Channel3 Shopping", description: "Shop products across the web", category: "Compras", domain: "channel3-shopping.com" },
  { id: "donedeal", name: "DoneDeal", description: "Find the most new & used cars", category: "Autos", domain: "donedeal.ie" },
  { id: "luxauto", name: "Luxauto", description: "Cars and moto to buy and lease", category: "Autos", domain: "luxauto.lu" },
  { id: "montreat-heating-and-cooling", name: "Montreat Heating and Cooling", description: "HVAC pricing and booking.", category: "Otros", domain: "montreat-heating-and-cooling.com" },
  { id: "tiendanube", name: "TiendaNube", description: "Gestiona tu tienda en línea", category: "Otros", domain: "tiendanube.com" },
  { id: "shipal", name: "Shipal", description: "Track any package by tracking", category: "Otros", domain: "shipal.com" },
  { id: "skylit-studio-custom-gifts", name: "Skylit Studio Custom Gifts", description: "Make a moment unforgettable", category: "Otros", domain: "skylit-studio-custom-gifts.com" },
  { id: "le-parisien", name: "Le Parisien", description: "Toute l'actualité en un clic", category: "Noticias", domain: "leparisien.fr" },
  { id: "hookradar", name: "HookRadar", description: "SMM and Ads creative research", category: "Otros", domain: "hookradar.com" },
  { id: "simplysefer", name: "SimplySefer", description: "Search seforim listings", category: "Inmuebles", domain: "simplysefer.com" },
  { id: "remodeleriq", name: "RemodelerIQ", description: "Is your contractor bid fair?", category: "Otros", domain: "remodeleriq.com" },
  { id: "ac-artificial-conscience", name: "AC - Artificial Conscience®", description: "The Christian Moral Layer", category: "Otros", domain: "ac-artificial-conscience.com" },
  { id: "app", name: "요기요", description: "배달할 때마다 포인트 적립", category: "Otros", domain: "yogiyo.co.kr" },
  { id: "nejo", name: "Nejo", description: "Stellenangebote durchsuchen", category: "Empleo", domain: "nejo.com" },
  { id: "imoveis-magiko-ia", name: "Imóveis Magiko IA", description: "Encontre imóveis com IA", category: "Inmuebles", domain: "imoveis-magiko-ia.com" },
  { id: "lifestyle-helper", name: "Lifestyle Helper", description: "Trusted tips for daily life", category: "Otros", domain: "lifestyle-helper.com" },
  { id: "boostermage", name: "Boostermage", description: "Compare UK MTG prices", category: "Otros", domain: "boostermage.com" },
  { id: "connectlinx", name: "Connectlinx", description: "Run your real estate business", category: "Inmuebles", domain: "connectlinx.com" },
  { id: "lalso-rsvp-invites", name: "Lalso RSVP — Invites", description: "Online invites, RSVPs & guests", category: "Otros", domain: "lalso-rsvp-invites.com" },
  { id: "pricey-monitor-history-alerts", name: "Pricey- monitor+history+alerts", description: "Track+watch shopping products", category: "Compras", domain: "pricey-monitor-history-alerts.com" },
  { id: "red-estelar", name: "Red Estelar", description: "Homes for sale or rent", category: "Inmuebles", domain: "red-estelar.com" },
  { id: "carsleuth", name: "CarSleuth", description: "Investigate used cars", category: "Autos", domain: "carsleuth.com" },
  { id: "a-z-dog-breeds", name: "A-Z Dog Breeds", description: "Every breed, all the details", category: "Otros", domain: "a-z-dog-breeds.com" },
  { id: "municibid", name: "Municibid", description: "Find government auctions", category: "Otros", domain: "municibid.com" },
  { id: "confused-com", name: "Confused.com", description: "Check your vehicle tax", category: "Autos", domain: "confused.com" },
  { id: "3byggetilbud-dk", name: "3byggetilbud.dk", description: "Find håndværkere hurtigt", category: "Otros", domain: "3byggetilbud.dk" },
  { id: "getir", name: "Getir", description: "delivery in minutes", category: "Otros", domain: "getir.com" },
  { id: "champfy", name: "Champfy", description: "Find Tennis|Pickleball partner", category: "Otros", domain: "champfy.com" },
  { id: "carslink-ai", name: "CarsLink.ai", description: "Search UK cars, vans & bikes", category: "Autos", domain: "carslink.ai" },
  { id: "batoo-used-boats", name: "Batoo - Used Boats", description: "Find and compare used boats", category: "Autos", domain: "batoo-used-boats.com" },
  { id: "perchli-property-search", name: "Perchli Property Search", description: "Search NI Properties", category: "Inmuebles", domain: "perchli-property-search.com" },
  { id: "closai", name: "Closai", description: "Personal Inventory Management", category: "Otros", domain: "closai.com" },
  { id: "meetup", name: "Meetup", description: "Find local social events", category: "Otros", domain: "meetup.com" },
  { id: "paardplaats-horse-finder", name: "Paardplaats Horse Finder", description: "Find horses for sale worldwide", category: "Otros", domain: "paardplaats-horse-finder.com" },
  { id: "justlife", name: "Justlife", description: "Find and book home services", category: "Otros", domain: "justlife.com" },
  { id: "landwirt-com", name: "Landwirt.com", description: "Find agricultural machinery", category: "Otros", domain: "landwirt.com" },
  { id: "safe2sign-contract-risk-check", name: "Safe2Sign: Contract Risk Check", description: "Review Agreement for Red Flags", category: "Otros", domain: "safe2sign-contract-risk-check.com" },
  { id: "spaartje", name: "Spaartje", description: "Compare grocery prices", category: "Comida", domain: "spaartje.com" },
  { id: "webuycars", name: "WeBuyCars", description: "Search cars and sell yours", category: "Autos", domain: "webuycars.co.za" },
  { id: "polypo", name: "Polypo", description: "Find your size. See your fit.", category: "Otros", domain: "polypo.com" },
  { id: "immobilien-immoprofessional", name: "Immobilien immoprofessional", description: "Find real estate across EU", category: "Inmuebles", domain: "immobilien-immoprofessional.com" },
  { id: "anvaya", name: "Anvaya", description: "Plan your multi-event Wedding", category: "Otros", domain: "anvaya.com" },
  { id: "standvirtual", name: "Standvirtual", description: "Your dream car in Standvirtual", category: "Autos", domain: "standvirtual.com" },
  { id: "dolphin-fitness", name: "Dolphin Fitness", description: "Shop fitness & wellbeing", category: "Compras", domain: "dolphin-fitness.com" },
  { id: "denison-yachting", name: "Denison Yachting", description: "Search yachts for sale", category: "Autos", domain: "denison-yachting.com" },
  { id: "din-bostad", name: "Din Bostad", description: "Find Swedish property listings", category: "Inmuebles", domain: "din-bostad.com" },
  { id: "fragella-discover-your-scent", name: "Fragella: Discover Your Scent", description: "Discover Your Signature Scent", category: "Otros", domain: "fragella-discover-your-scent.com" },
  { id: "patriot-conceptions", name: "Patriot Conceptions", description: "Preview profiles", category: "Otros", domain: "patriot-conceptions.com" },
  { id: "elfai-fashion-stylist", name: "elfai: Fashion Stylist", description: "Find personalized outfits", category: "Compras", domain: "elfai-fashion-stylist.com" },
  { id: "klinger-vogt-immobilien", name: "Klinger-Vogt Immobilien", description: "Rhine-Neckar Real Estate", category: "Inmuebles", domain: "klinger-vogt-immobilien.com" },
  { id: "trocafone", name: "Trocafone", description: "Find pre-owned smartphones", category: "Otros", domain: "trocafone.com" },
  { id: "samrum", name: "SAMRUM", description: "Family personality profiles", category: "Otros", domain: "samrum.com" },
  { id: "liftosaur", name: "Liftosaur", description: "Create scriptable workouts", category: "Otros", domain: "liftosaur.com" },
  { id: "journaling-with-medome", name: "Journaling with Medome", description: "Build Your Daily Journal", category: "Otros", domain: "journaling-with-medome.com" },
  { id: "horizon-shield", name: "HORIZON SHIELD", description: "Check Japan reform estimates", category: "Otros", domain: "horizon-shield.com" },
  { id: "tessie", name: "Tessie", description: "Access and control your Tesla", category: "Autos", domain: "tessie.com" },
  { id: "cliqueimudei", name: "CliqueiMudei", description: "Find properties and homes", category: "Inmuebles", domain: "cliqueimudei.com" },
  { id: "rolf-automobile-showroom", name: "Rolf Automobile Showroom", description: "Find cars from our inventory", category: "Autos", domain: "rolf-automobile-showroom.com" },
  { id: "imovirtual", name: "Imovirtual", description: "Find real estate in Portugal", category: "Inmuebles", domain: "imovirtual.com" },
  { id: "athome", name: "atHome", description: "Find properties to buy or rent", category: "Inmuebles", domain: "athome.lu" },
  { id: "eydost-esim", name: "Eydost Esim", description: "Instant eSIM in 150+ countries", category: "Otros", domain: "eydost-esim.com" },
  { id: "alldiscgolf", name: "AllDiscGolf", description: "Compare disc golf prices", category: "Otros", domain: "alldiscgolf.com" },
  { id: "immo-der-vr-bank-rhein-neckar", name: "Immo der VR Bank Rhein-Neckar", description: "Properties in the Rhine-Neckar", category: "Inmuebles", domain: "immo-der-vr-bank-rhein-neckar.com" },
  { id: "doctorsim-mobile-topups", name: "doctorSIM Mobile Topups", description: "Mobile Top-ups and Recharges", category: "Otros", domain: "doctorsim-mobile-topups.com" },
  { id: "immobiliare-it", name: "Immobiliare.it", description: "The N.1 for selling and buying", category: "Inmuebles", domain: "immobiliare.it" },
  { id: "the-lonely-door", name: "The Lonely Door", description: "Enter through The Lonely Door", category: "Otros", domain: "the-lonely-door.com" },
  { id: "app-2", name: "무신사", description: "Find by style, pick by reviews", category: "Otros", domain: "musinsa.com" },
  { id: "nash-agent", name: "Nash Agent", description: "AI-powered shopping agent", category: "Compras", domain: "nash-agent.com" },
  { id: "mycolive", name: "MYCOlive", description: "Home Rental Platform", category: "Inmuebles", domain: "mycolive.com" },
  { id: "amore-mall", name: "아모레몰 AMORE MALL", description: "공식 브랜드 쇼핑부터 스마트 뷰티 케어까지", category: "Compras", domain: "amoremall.com" },
  { id: "internshala", name: "Internshala", description: "Find internships & jobs", category: "Empleo", domain: "internshala.com" },
  { id: "metz-immobilien", name: "Metz Immobilien", description: "Frankfurt Properties", category: "Inmuebles", domain: "metz-immobilien.com" },
  { id: "vaktim", name: "Vaktim", description: "Quran and prayer times", category: "Otros", domain: "vaktim.com" },
  { id: "the-wildfire-tracker", name: "The Wildfire tracker", description: "Fire map", category: "Otros", domain: "the-wildfire-tracker.com" },
  { id: "break-the-web-news", name: "Break The Web News", description: "Get the latest news and trends", category: "Noticias", domain: "break-the-web-news.com" },
  { id: "vw-sign-drive", name: "VW Sign & Drive", description: "Find VW car subscription plans", category: "Autos", domain: "volkswagen.com" },
  { id: "mondoir-art", name: "Mondoir.art", description: "Find artworks for your space", category: "Otros", domain: "mondoir.art" },
  { id: "smartcustomer", name: "SmartCustomer", description: "Business ratings and reviews", category: "Otros", domain: "smartcustomer.com" },
  { id: "scangym", name: "ScanGym", description: "Find and book gym day passes", category: "Otros", domain: "scangym.com" },
  { id: "automotion", name: "AutoMotion", description: "Car Maintenance & Repair", category: "Autos", domain: "automotion.com" },
  { id: "promocodes-com", name: "Promocodes.com", description: "Find verified promo codes", category: "Compras", domain: "promocodes.com" },
  { id: "penny", name: "Penny", description: "Shop deals, track prices", category: "Compras", domain: "penny.de" },
  { id: "dispatcher-city", name: "Dispatcher.City", description: "Search Berlin property", category: "Inmuebles", domain: "dispatcher.city" },
  { id: "saltybytes", name: "SaltyBytes", description: "Find and save real recipes", category: "Comida", domain: "saltybytes.com" },
  { id: "spee24-shopping", name: "Spee24 Shopping", description: "Find and buy products easily", category: "Compras", domain: "spee24-shopping.com" },
  { id: "trovaprezzi-it", name: "Trovaprezzi.it", description: "Confronta prezzi prodotti", category: "Otros", domain: "trovaprezzi.it" },
  { id: "mrv", name: "MRV", description: "Conecta você ao apê ideal", category: "Compras", domain: "mrv.com" },
  { id: "botala-by-dyskute", name: "Botala by dyskute", description: "Commandez partout", category: "Otros", domain: "botala-by-dyskute.com" },
  { id: "artue", name: "artue", description: "Find art with natural language", category: "Otros", domain: "artue.com" },
  { id: "digimarket", name: "Digimarket", description: "Find industrial stock", category: "Compras", domain: "digimarket.com" },
  { id: "cora", name: "Cora", description: "Personal health coach", category: "Otros", domain: "cora.com" },
  { id: "pantry-persona", name: "Pantry Persona", description: "Meal Plans, Recipes, Inventory", category: "Comida", domain: "pantry-persona.com" },
  { id: "milanuncios", name: "Milanuncios", description: "Search second hand items", category: "Otros", domain: "milanuncios.com" },
  { id: "fotocasa", name: "Fotocasa", description: "Find properties to buy or rent", category: "Inmuebles", domain: "fotocasa.es" },
  { id: "mimove", name: "MiMove", description: "Sale in Spain and Portugal", category: "Otros", domain: "mimove.com" },
  { id: "tuespaciopr", name: "TuEspacioPR", description: "Search Puerto Rico Listings", category: "Inmuebles", domain: "tuespaciopr.com" },
  { id: "home-connect", name: "Home Connect", description: "Bosch, Siemens, Gaggenau, NEFF", category: "Otros", domain: "home-connect.com" },
  { id: "rifo-home", name: "RIFO Home", description: "Find Homes to Buy and Rent", category: "Inmuebles", domain: "rifo-home.com" },
  { id: "olx-india", name: "OLX India", description: "Search OLX listings", category: "Inmuebles", domain: "olx.in" },
  { id: "deglaze", name: "Deglaze", description: "Chat with your recipe library", category: "Comida", domain: "deglaze.com" },
  { id: "airtasker", name: "Airtasker", description: "Post tasks and hire taskers", category: "Otros", domain: "airtasker.com" },
  { id: "karaca", name: "Karaca", description: "Karaca Ürünlerini Keşfet!", category: "Otros", domain: "karaca.com" },
  { id: "nuvemshop", name: "Nuvemshop", description: "Gerencie sua loja online", category: "Compras", domain: "nuvemshop.com" },
  { id: "housetospot-immobilien", name: "HouseToSpot Immobilien", description: "Find the right property faster", category: "Inmuebles", domain: "housetospot-immobilien.com" },
  { id: "bandsintown", name: "Bandsintown", description: "Find concerts and tour dates", category: "Otros", domain: "bandsintown.com" },
  { id: "catholic-index", name: "Catholic Index", description: "Find Mass times and churches", category: "Otros", domain: "catholic-index.com" },
  { id: "skillmap-pro", name: "Skillmap Pro", description: "Servicios y trabajo en Chile", category: "Empleo", domain: "skillmap-pro.com" },
  { id: "nameeasy", name: "NameEasy", description: "Find Indian Baby Names", category: "Otros", domain: "nameeasy.com" },
  { id: "japanbox-kz", name: "JapanBox.kz", description: "Shop Japan via chat", category: "Compras", domain: "japanbox.kz" },
  { id: "dewa", name: "DEWA", description: "View bills, services and more.", category: "Otros", domain: "dewa.gov.ae" },
  { id: "keuzehulp-studio", name: "Keuzehulp Studio", description: "Hulp bij keuzes", category: "Otros", domain: "keuzehulp-studio.com" },
  { id: "lfmall", name: "LFmall", description: "나를 나답게 만드는 취향 발견, LFmall AI 쇼핑", category: "Compras", domain: "lfmall.co.kr" },
  { id: "onyx-coach", name: "Onyx Coach", description: "Coach clients and workouts", category: "Otros", domain: "onyx-coach.com" },
  { id: "otomoto", name: "OTOMOTO", description: "Znajdź auto marzeń w OTOMOTO", category: "Autos", domain: "otomoto.pl" },
  { id: "carwale", name: "CarWale", description: "Find, research & compare cars", category: "Autos", domain: "carwale.com" },
  { id: "background-changer", name: "Background Changer", description: "Discover website themes", category: "Otros", domain: "background-changer.com" },
  { id: "simply-wedding", name: "Simply-Wedding", description: "Heiraten leicht gemacht", category: "Otros", domain: "simply-wedding.com" },
  { id: "kingpin-market", name: "Kingpin Market", description: "Fingerboard marketplace", category: "Compras", domain: "kingpin-market.com" },
  { id: "hepapal", name: "HepaPal", description: "Track drinking gently", category: "Otros", domain: "hepapal.com" },
  { id: "casepoint", name: "Casepoint", description: "eDiscovery, Legal Hold & FOIA", category: "Otros", domain: "casepoint.com" },
  { id: "webaz-shopping", name: "WebAZ Shopping", description: "Find reviewed physical goods", category: "Compras", domain: "webaz-shopping.com" },
  { id: "korea-concierge", name: "Korea Concierge", description: "Korea help with proof", category: "Otros", domain: "korea-concierge.com" },
  { id: "luma", name: "Luma", description: "Find and manage events", category: "Otros", domain: "lu.ma" },
  { id: "tessun-immobilien", name: "Tessun Immobilien", description: "Properties Munich & ILT", category: "Inmuebles", domain: "tessun-immobilien.com" },
  { id: "klinger-immobilien", name: "KLINGER Immobilien", description: "Berlin Area Properties", category: "Inmuebles", domain: "klinger-immobilien.com" },
  { id: "nicebabyname-nameology", name: "NiceBabyName — Nameology", description: "Read baby names by nameology", category: "Otros", domain: "nicebabyname-nameology.com" },
  { id: "immobilien-franzen", name: "Immobilien Franzen", description: "Eifel and Trier Properties", category: "Inmuebles", domain: "immobilien-franzen.com" },
  { id: "clickdealer", name: "ClickDealer", description: "Search used cars in the UK", category: "Autos", domain: "clickdealer.com" },
  { id: "peristyle-grocery-cart", name: "Peristyle Grocery Cart", description: "Recipes into a grocery cart", category: "Comida", domain: "peristyle-grocery-cart.com" },
  { id: "who-what-wear", name: "Who What Wear", description: "Editor picks, tuned to you", category: "Otros", domain: "whowhatwear.com" },
  { id: "magneto-empleos", name: "Magneto Empleos", description: "Search Jobs with AI", category: "Empleo", domain: "magneto365.com" },
  { id: "cashback-hive-deals-coupons", name: "Cashback Hive: Deals & Coupons", description: "Save on every purchase", category: "Compras", domain: "cashback-hive-deals-coupons.com" },
  { id: "1-2-3-cook-bake-food-to-eat", name: "1-2-3-Cook+Bake Food to eat!", description: "Find recipes+baking+meals+prep", category: "Comida", domain: "1-2-3-cook-bake-food-to-eat.com" },
  { id: "app-3", name: "전자랜드", description: "전문가가 고르고, 혜택은 더하고", category: "Otros", domain: "etland.co.kr" },
  { id: "pearl-auto", name: "Pearl Auto", description: "Verify car answers", category: "Autos", domain: "pearl-auto.com" },
  { id: "robin", name: "robin", description: "Finds your next dream home", category: "Otros", domain: "robin.com" },
  { id: "hepsiemlak", name: "hepsiemlak", description: "Find Your Home with Ease", category: "Otros", domain: "hepsiemlak.com" },
  { id: "clutch", name: "Clutch", description: "Buy & sell used cars in Canada", category: "Autos", domain: "clutch.ca" },
  { id: "midi-libre", name: "Midi Libre", description: "L’info locale en continu", category: "Noticias", domain: "midilibre.fr" },
  { id: "spoonpal", name: "SpoonPal", description: "Analyze meals and get recipes", category: "Comida", domain: "spoonpal.com" },
  { id: "annstracts", name: "Annstracts", description: "Discover abstract photography", category: "Otros", domain: "annstracts.com" },
  { id: "boulanger-achat-en-ligne", name: "Boulanger - Achat en ligne", description: "Electroménager & Multimedia", category: "Otros", domain: "boulanger.com" },
  { id: "dominio-tech-delivery", name: "Dominio Tech Delivery", description: "Peça comida pelo ChatGPT", category: "Otros", domain: "dominio-tech-delivery.com" },
  { id: "love-and-lemons", name: "Love and Lemons", description: "Find recipes and plan meals", category: "Comida", domain: "loveandlemons.com" },
  { id: "lucid-beads", name: "Lucid Beads", description: "Create your dream bracelet", category: "Otros", domain: "lucid-beads.com" },
  { id: "app-4", name: "올리브영", description: "Discover beauty, Find yours", category: "Compras", domain: "oliveyoung.co.kr" },
  { id: "dillr", name: "Dillr", description: "Save recipes, plan meals, cook", category: "Comida", domain: "dillr.com" },
  { id: "nipp", name: "$nipp", description: "Find Deals. Earn Rewards.", category: "Compras", domain: "nipp.com" },
  { id: "cars24", name: "CARS24", description: "Find your dream car", category: "Autos", domain: "cars24.com" },
  { id: "cellfusion-c", name: "CellFusion C", description: "Skincare picks", category: "Otros", domain: "cellfusion-c.com" },
  { id: "apexlog", name: "ApexLog", description: "Query your track day logbook", category: "Otros", domain: "apexlog.com" },
  { id: "muju", name: "Muju", description: "Discover and order locally", category: "Otros", domain: "muju.com" },
  { id: "onx-offroad", name: "onX Offroad", description: "Find offroad trails", category: "Otros", domain: "onxmaps.com" },
  { id: "product-link-expander", name: "Product Link Expander", description: "Expand product links", category: "Compras", domain: "product-link-expander.com" },
  { id: "foodora", name: "foodora", description: "Find restaurants and menus", category: "Comida", domain: "foodora.com" },
  { id: "progressive-clarity", name: "Progressive Clarity", description: "Orient, explore naturally", category: "Otros", domain: "progressive-clarity.com" },
  { id: "anybarcodescanner", name: "AnyBarcodeScanner", description: "Scan and discuss products", category: "Compras", domain: "anybarcodescanner.com" },
  { id: "cj", name: "CJ온스타일", description: "Live shopping, your style", category: "Compras", domain: "onstyle.co.kr" },
  { id: "stars-in-hands-gift-studio", name: "Stars In Hands Gift Studio", description: "Personalized gift proofs", category: "Otros", domain: "stars-in-hands-gift-studio.com" },
  { id: "pacelab-intervals", name: "Pacelab Intervals", description: "Create interval workouts", category: "Otros", domain: "pacelab-intervals.com" },
  { id: "inoreader", name: "Inoreader", description: "Build your own newsfeed", category: "Noticias", domain: "inoreader.com" },
  { id: "rilev", name: "Rilev", description: "Personalize your chats", category: "Otros", domain: "rilev.com" },
  { id: "outfit-lens", name: "Outfit Lens", description: "Snap a look, shop it instantly", category: "Compras", domain: "outfit-lens.com" },
  { id: "anyreg", name: "AnyReg", description: "Get number plate vehicle info!", category: "Autos", domain: "anyreg.com" },
  { id: "fryd", name: "Fryd", description: "Your Gardening Companion", category: "Otros", domain: "fryd.com" },
  { id: "quintoandar", name: "QuintoAndar", description: "Find your ideal home", category: "Inmuebles", domain: "quintoandar.com.br" },
  { id: "emlakjet", name: "Emlakjet", description: "Search and filter real estate", category: "Inmuebles", domain: "emlakjet.com" },
  { id: "wallector", name: "Wallector", description: "Discover and buy fine art", category: "Compras", domain: "wallector.com" },
  { id: "bayut-ksa", name: "Bayut KSA", description: "Find homes in the KSA", category: "Inmuebles", domain: "bayut.sa" },
  { id: "drums-kit-learn-improve-w-ai", name: "Drums kit- Learn+improve w AI!", description: "Coach+Practice play,beat,fills", category: "Otros", domain: "drums-kit-learn-improve-w-ai.com" },
  { id: "rotv-guide", name: "RoTV Guide", description: "Live Romanian TV guide", category: "Otros", domain: "rotv-guide.com" },
  { id: "refermate", name: "Refermate", description: "Find deals and rewards", category: "Compras", domain: "refermate.com" },
  { id: "spotahome", name: "Spotahome", description: "Find rental homes", category: "Inmuebles", domain: "spotahome.com" },
  { id: "crbonfree", name: "Crbonfree", description: "Estimate and offset CO2", category: "Otros", domain: "crbonfree.com" },
  { id: "remode", name: "Remode", description: "Shop any outfit from a photo", category: "Compras", domain: "remode.com" },
  { id: "car-handshake", name: "Car Handshake", description: "Find cars for sale near you", category: "Autos", domain: "car-handshake.com" },
  { id: "myregistry-com", name: "MyRegistry.com", description: "All Stores, One Registry®", category: "Compras", domain: "myregistry.com" },
  { id: "gs", name: "우리동네GS", description: "우리 일상 속 GS를 더 가깝게", category: "Otros", domain: "gsretail.com" },
  { id: "maysynthel-shopping", name: "Maysynthel Shopping", description: "Maysynthel fashion & lifestyle", category: "Compras", domain: "maysynthel-shopping.com" },
  { id: "print-com", name: "Print.com", description: "Explore and price printing", category: "Otros", domain: "print.com" },
  { id: "wild-calf-coffee", name: "Wild Calf Coffee", description: "Find and brew better coffee", category: "Comida", domain: "wild-calf-coffee.com" },
  { id: "cand-reciclam", name: "Când Reciclăm", description: "Bucharest recycling schedules", category: "Otros", domain: "cand-reciclam.com" },
  { id: "chaiz", name: "Chaiz", description: "Compare car warranty quotes", category: "Autos", domain: "chaiz.com" },
  { id: "grailpeople-shopping", name: "GrailPeople Shopping", description: "Find honest product reviews", category: "Compras", domain: "grailpeople-shopping.com" },
  { id: "sangria", name: "Sangria", description: "Buy products online", category: "Compras", domain: "sangria.com" },
  { id: "experteer", name: "Experteer", description: "Find Your Next Leadership Role", category: "Empleo", domain: "experteer.com" },
  { id: "gathrd", name: "Gathrd", description: "Shop, Save & Track Products", category: "Compras", domain: "gathrd.com" },
  { id: "skw-immobilien", name: "SKW Immobilien", description: "Gütersloh properties", category: "Inmuebles", domain: "skw-immobilien.com" },
  { id: "tawadoo-buy-sell-auctions", name: "Tawadoo: Buy, Sell, Auctions", description: "Morocco classifieds, auctions", category: "Compras", domain: "tawadoo-buy-sell-auctions.com" },
  { id: "product-hunt", name: "Product Hunt", description: "The best new products in tech.", category: "Compras", domain: "producthunt.com" },
  { id: "3-2-1-go-stopwatch", name: "3-2-1 Go Stopwatch", description: "Ready... set... go!", category: "Otros", domain: "3-2-1-go-stopwatch.com" },
  { id: "carparts-com", name: "Carparts.com", description: "Find best quality auto parts", category: "Autos", domain: "carparts.com" },
  { id: "pc-express", name: "PC Express", description: "Buy groceries online", category: "Comida", domain: "pc-express.com" },
  { id: "zola", name: "Zola", description: "Find wedding vendors", category: "Otros", domain: "zola.com" },
  { id: "imeb-eva-buchholz", name: "IMEB - Eva Buchholz", description: "Real estate expert for Munich", category: "Inmuebles", domain: "imeb-eva-buchholz.com" },
  { id: "la-centrale", name: "La Centrale", description: "Trouver votre véhicule", category: "Otros", domain: "lacentrale.fr" },
  { id: "real-random", name: "Real Random", description: "Generate truly random values", category: "Otros", domain: "real-random.com" },
  { id: "diretora-criativa-sell-pro", name: "Diretora Criativa Sell Pro", description: "Imagens CRO para marketplaces", category: "Compras", domain: "diretora-criativa-sell-pro.com" },
  { id: "public-storage", name: "Public Storage", description: "Find self-storage space units", category: "Otros", domain: "publicstorage.com" },
  { id: "workopia", name: "Workopia", description: "Jobs, career advice & resumes", category: "Empleo", domain: "workopia.com" },
  { id: "buywise", name: "BuyWise", description: "Find best prices, real reviews", category: "Compras", domain: "buywise.com" },
  { id: "la-depeche-du-midi", name: "La Dépêche du Midi", description: "Toute l’actualité en continu", category: "Noticias", domain: "ladepeche.fr" },
  { id: "wellness-coach", name: "Wellness Coach", description: "On-demand wellness guidance", category: "Otros", domain: "wellness-coach.com" },
  { id: "lott-immobilien", name: "Lott Immobilien", description: "Leer to Oldenburg properties", category: "Inmuebles", domain: "lott-immobilien.com" },
  { id: "engel-volkers", name: "Engel & Völkers", description: "Find property listings", category: "Inmuebles", domain: "engelvoelkers.com" },
  { id: "app-5", name: "Реалистимо", description: "Realestate properties Bulgaria", category: "Inmuebles", domain: "app-5.com" },
  { id: "gethumandesign-com", name: "gethumandesign.com", description: "Explore your human design", category: "Otros", domain: "gethumandesign.com" },
  { id: "laundryheap", name: "Laundryheap", description: "Book laundry pickups", category: "Otros", domain: "laundryheap.com" },
  { id: "tixel", name: "Tixel", description: "Find Tixel tickets", category: "Otros", domain: "tixel.com" },
  { id: "calories-club", name: "Calories Club", description: "Track meals and nutrition", category: "Comida", domain: "calories-club.com" },
  { id: "endurance-planner", name: "Endurance Planner", description: "Plan your endurance", category: "Otros", domain: "endurance-planner.com" },
  { id: "monnier-paris", name: "Monnier Paris", description: "Luxury catalog in ChatGPT", category: "Otros", domain: "monnier-paris.com" },
  { id: "spacecloud-global", name: "SpaceCloud Global", description: "International rental spaces", category: "Empleo", domain: "spacecloud-global.com" },
  { id: "greystar-apartment-scout", name: "Greystar Apartment Scout", description: "Search over 1M apartments", category: "Inmuebles", domain: "greystar-apartment-scout.com" },
  { id: "rakhys", name: "Rakhys", description: "Find best electronics prices", category: "Otros", domain: "rakhys.com" },
  { id: "website-launches", name: "Website Launches", description: "Check launch dates & trust", category: "Otros", domain: "website-launches.com" },
  { id: "chefjojo", name: "ChefJoJo", description: "Your magical kitchen sidekick", category: "Otros", domain: "chefjojo.com" },
  { id: "barfoot-thompson-homes", name: "Barfoot & Thompson Homes", description: "Search NZ property listings", category: "Inmuebles", domain: "barfoot-thompson-homes.com" },
  { id: "carsguide", name: "CarsGuide", description: "Find cars, prices and reviews.", category: "Autos", domain: "carsguide.com.au" },
  { id: "angler-adventures-lure-guide", name: "Angler Adventures: Lure Guide", description: "Match lures to lake conditions", category: "Otros", domain: "angler-adventures-lure-guide.com" },
  { id: "daft-ie", name: "Daft.ie", description: "Find Irish Properties for sale", category: "Inmuebles", domain: "daft.ie" },
  { id: "raptive-food", name: "Raptive Food", description: "Find recipes you can trust", category: "Comida", domain: "raptive-food.com" },
  { id: "0-100-wifi-internet-speed-test", name: "0-100 WiFi Internet Speed Test", description: "Broadband, Online Network, 5G", category: "Empleo", domain: "0-100-wifi-internet-speed-test.com" },
  { id: "bayut", name: "Bayut", description: "Find homes in the UAE", category: "Inmuebles", domain: "bayut.com" },
  { id: "foodpanda", name: "foodpanda", description: "Find restaurants and menus", category: "Comida", domain: "foodpanda.com" },
  { id: "trail-hits-bicycle-maintenance", name: "Trail Hits:Bicycle Maintenance", description: "Track your Bike's maintenance", category: "Otros", domain: "trail-hits-bicycle-maintenance.com" },
  { id: "rozetka", name: "Rozetka: інтернет гіпермаркет", description: "Search and order products", category: "Compras", domain: "rozetka.com.ua" },
  { id: "zinde-ai-free-calorie-tracker", name: "Zinde AI Free Calorie Tracker", description: "Track meals, water, exercise", category: "Comida", domain: "zinde-ai-free-calorie-tracker.com" },
  { id: "eland-mall", name: "이랜드몰 ELAND MALL", description: "사는 즐거움이 있는 이랜드 공식 라이프스타일 몰", category: "Compras", domain: "elandmall.com" },
  { id: "motos-net", name: "motos.net", description: "Find new and used motorbikes", category: "Autos", domain: "motos.net" },
  { id: "kokiko", name: "Kokiko", description: "Find beauty products fast", category: "Compras", domain: "kokiko.com" },
  { id: "autovit-ro", name: "Autovit.ro", description: "Find your dream car in Autovit", category: "Autos", domain: "autovit.ro" },
  { id: "shopback", name: "ShopBack", description: "Get cashback for your shopping", category: "Compras", domain: "shopback.com" },
  { id: "wundercinemate", name: "WunderCineMate", description: "Discover and manage Movies!", category: "Otros", domain: "wundercinemate.com" },
  { id: "letra-da-lei", name: "Letra da Lei", description: "Brazilian legal research", category: "Otros", domain: "letra-da-lei.com" },
  { id: "gumtree", name: "Gumtree", description: "Search Gumtree listings", category: "Inmuebles", domain: "gumtree.com" },
]
