import { describe, expect, it } from "vitest"

import {
  detectWorkspaceSchema,
  fieldLabel,
  parsePrismaModels,
} from "@/lib/code-agent/workspace-schema"

const PRISMA = `// Generated by siraGPT Builder · E3
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Pet {
  id        String   @id @default(cuid())
  name      String
  species   String?
  visits    Visit[]
  createdAt DateTime @default(now())
  @@index([name])
}

model Visit {
  id     String @id @default(cuid())
  reason String
  pet    Pet    @relation(fields: [petId], references: [id])
  petId  String @unique
}
`

describe("parsePrismaModels", () => {
  it("parses models with fields, flags and relations", () => {
    const models = parsePrismaModels(PRISMA)
    expect(models.map((m) => m.name)).toEqual(["Pet", "Visit"])

    const pet = models[0]
    const id = pet.fields.find((f) => f.name === "id")!
    expect(id.isId).toBe(true)
    expect(id.hasDefault).toBe(true)
    expect(id.type).toBe("String")

    const species = pet.fields.find((f) => f.name === "species")!
    expect(species.optional).toBe(true)
    expect(species.list).toBe(false)

    const visits = pet.fields.find((f) => f.name === "visits")!
    expect(visits.list).toBe(true)
    expect(visits.relation).toBe("Visit")
  })

  it("skips block attributes and comments", () => {
    const [pet] = parsePrismaModels(PRISMA)
    expect(pet.fields.some((f) => f.name.startsWith("@@"))).toBe(false)
    expect(pet.fields).toHaveLength(5)
  })

  it("marks @unique and detects relation via @relation attr", () => {
    const visit = parsePrismaModels(PRISMA)[1]
    expect(visit.fields.find((f) => f.name === "petId")!.isUnique).toBe(true)
    expect(visit.fields.find((f) => f.name === "pet")!.relation).toBe("Pet")
  })

  it("tolerates malformed input without throwing", () => {
    expect(parsePrismaModels("")).toEqual([])
    expect(parsePrismaModels("model Broken {")).toEqual([])
    expect(parsePrismaModels("nonsense ???")).toEqual([])
  })
})

describe("detectWorkspaceSchema", () => {
  it("prefers prisma schema when present", () => {
    const schema = detectWorkspaceSchema({
      "prisma/schema.prisma": { content: PRISMA },
      "app/api/pets/route.ts": { content: "export {}" },
    })
    expect(schema?.source).toBe("prisma")
    expect(schema?.path).toBe("prisma/schema.prisma")
    expect(schema?.models).toHaveLength(2)
  })

  it("falls back to api routes + store seed fields", () => {
    const schema = detectWorkspaceSchema({
      "app/api/pets/route.ts": { content: "export {}" },
      "app/api/pet-owners/route.ts": { content: "export {}" },
      "lib/store.ts": {
        content: `export const store = { "pets": [ { id: "1", name: "Rex", species: "dog" } ], "pet-owners": [ { id: "1", fullName: "Ana" } ] }`,
      },
    })
    expect(schema?.source).toBe("api-routes")
    expect(schema?.models.map((m) => m.name)).toEqual(["PetOwners", "Pets"])
    const pets = schema!.models.find((m) => m.name === "Pets")!
    expect(pets.fields.map((f) => f.name)).toEqual(["id", "name", "species"])
    const owners = schema!.models.find((m) => m.name === "PetOwners")!
    expect(owners.fields.map((f) => f.name)).toEqual(["id", "fullName"])
  })

  it("returns null when the workspace has no recognisable model", () => {
    expect(detectWorkspaceSchema({ "src/App.tsx": { content: "export default 1" } })).toBeNull()
    expect(detectWorkspaceSchema({})).toBeNull()
    expect(detectWorkspaceSchema(null)).toBeNull()
  })

  it("accepts plain-string file maps too", () => {
    const schema = detectWorkspaceSchema({ "prisma/schema.prisma": PRISMA })
    expect(schema?.models).toHaveLength(2)
  })
})

describe("fieldLabel", () => {
  it("renders compact labels", () => {
    const [pet] = parsePrismaModels(PRISMA)
    expect(fieldLabel(pet.fields.find((f) => f.name === "species")!)).toBe("species: String?")
    expect(fieldLabel(pet.fields.find((f) => f.name === "visits")!)).toBe("visits: Visit[]")
    expect(fieldLabel(pet.fields.find((f) => f.name === "id")!)).toBe("id: String")
  })
})
